# New Emojis. Up to date with emoji-js.json as of 2/16/2018
# TODO: Recategorize emojis to the appropriate files.

require 'rumoji/emoji'
require 'set'

module Rumoji
  class Emoji
    NEWMOJI = SortedSet[
      self.new(Regexp.escape("\u{002A FE0F 20E3}"), [:keycap_star]),
      self.new("\u{1F1FA 1F1F3}", [:"flag-un"]),
      self.new("\u{1F324 FE0F}", [:sun_small_cloud]),
      self.new("\u{1F325 FE0F}", [:sun_behind_cloud]),
      self.new("\u{1F326 FE0F}", [:sun_behind_rain_cloud]),
      self.new("\u{1F329 FE0F}", [:lightning_cloud]),
      self.new("\u{1F32A FE0F}", [:tornado_cloud]),
      self.new("\u{1F373}", [:cooking]),
      self.new("\u{1F373}", [:fried_egg]),
      self.new("\u{1F3C3 200D 2640 FE0F}", [:"woman-running"]),
      self.new("\u{1F3C3 200D 2642 FE0F}", [:"man-running"]),
      self.new("\u{1F3C4 200D 2640 FE0F}", [:"woman-surfing"]),
      self.new("\u{1F3C4 200D 2642 FE0F}", [:"man-surfing"]),
      self.new("\u{1F3CA 200D 2640 FE0F}", [:"woman-swimming"]),
      self.new("\u{1F3CA 200D 2642 FE0F}", [:"man-swimming"]),
      self.new("\u{1F3CB FE0F 200D 2640 FE0F}", [:"woman-lifting-weights"]),
      self.new("\u{1F3CB FE0F 200D 2642 FE0F}", [:"man-lifting-weights"]),
      self.new("\u{1F3CC FE0F 200D 2640 FE0F}", [:"woman-golfing"]),
      self.new("\u{1F3CC FE0F 200D 2642 FE0F}", [:"man-golfing"]),
      self.new("\u{1F3EE}", [:lantern]),
      self.new("\u{1F3F3 FE0F 200D 1F308}", [:"rainbow-flag"]),
      self.new("\u{1F3F4 E0067 E0062 E0065 E006E E0067 E007F}", [:"flag-england"]),
      self.new("\u{1F3F4 E0067 E0062 E0073 E0063 E0074 E007F}", [:"flag-scotland"]),
      self.new("\u{1F3F4 E0067 E0062 E0077 E006C E0073 E007F}", [:"flag-wales"]),
      self.new("\u{1F3FB}", [:"skin-tone-2"]),
      self.new("\u{1F3FC}", [:"skin-tone-3"]),
      self.new("\u{1F3FD}", [:"skin-tone-4"]),
      self.new("\u{1F3FE}", [:"skin-tone-5"]),
      self.new("\u{1F3FF}", [:"skin-tone-6"]),
      self.new("\u{1F401}", [:mouse2]),
      self.new("\u{1F404}", [:cow2]),
      self.new("\u{1F405}", [:tiger2]),
      self.new("\u{1F407}", [:rabbit2]),
      self.new("\u{1F408}", [:cat2]),
      self.new("\u{1F40B}", [:whale2]),
      self.new("\u{1F415}", [:dog2]),
      self.new("\u{1F416}", [:pig2]),
      self.new("\u{1F42C}", [:flipper]),
      self.new("\u{1F441 FE0F 200D 1F5E8 FE0F}", [:"eye-in-speech-bubble"]),
      self.new("\u{1F44D}", [:"+1"]),
      self.new("\u{1F468 200D 1F33E}", [:"male-farmer"]),
      self.new("\u{1F468 200D 1F373}", [:"male-cook"]),
      self.new("\u{1F468 200D 1F393}", [:"male-student"]),
      self.new("\u{1F468 200D 1F3A4}", [:"male-singer"]),
      self.new("\u{1F468 200D 1F3A8}", [:"male-artist"]),
      self.new("\u{1F468 200D 1F3EB}", [:"male-teacher"]),
      self.new("\u{1F468 200D 1F3ED}", [:"male-factory-worker"]),
      self.new("\u{1F468 200D 1F466 200D 1F466}", [:"man-boy-boy"]),
      self.new("\u{1F468 200D 1F466}", [:"man-boy"]),
      self.new("\u{1F468 200D 1F467 200D 1F466}", [:"man-girl-boy"]),
      self.new("\u{1F468 200D 1F467 200D 1F467}", [:"man-girl-girl"]),
      self.new("\u{1F468 200D 1F467}", [:"man-girl"]),
      self.new("\u{1F468 200D 1F469 200D 1F466}", [:family]),
      self.new("\u{1F468 200D 1F469 200D 1F466}", [:"man-woman-boy"]),
      self.new("\u{1F468 200D 1F4BB}", [:"male-technologist"]),
      self.new("\u{1F468 200D 1F4BC}", [:"male-office-worker"]),
      self.new("\u{1F468 200D 1F527}", [:"male-mechanic"]),
      self.new("\u{1F468 200D 1F52C}", [:"male-scientist"]),
      self.new("\u{1F468 200D 1F680}", [:"male-astronaut"]),
      self.new("\u{1F468 200D 1F692}", [:"male-firefighter"]),
      self.new("\u{1F468 200D 2695 FE0F}", [:"male-doctor"]),
      self.new("\u{1F468 200D 2696 FE0F}", [:"male-judge"]),
      self.new("\u{1F468 200D 2708 FE0F}", [:"male-pilot"]),
      self.new("\u{1F469 200D 1F33E}", [:"female-farmer"]),
      self.new("\u{1F469 200D 1F373}", [:"female-cook"]),
      self.new("\u{1F469 200D 1F393}", [:"female-student"]),
      self.new("\u{1F469 200D 1F3A4}", [:"female-singer"]),
      self.new("\u{1F469 200D 1F3A8}", [:"female-artist"]),
      self.new("\u{1F469 200D 1F3EB}", [:"female-teacher"]),
      self.new("\u{1F469 200D 1F3ED}", [:"female-factory-worker"]),
      self.new("\u{1F469 200D 1F466 200D 1F466}", [:"woman-boy-boy"]),
      self.new("\u{1F469 200D 1F466}", [:"woman-boy"]),
      self.new("\u{1F469 200D 1F467 200D 1F466}", [:"woman-girl-boy"]),
      self.new("\u{1F469 200D 1F467 200D 1F467}", [:"woman-girl-girl"]),
      self.new("\u{1F469 200D 1F467}", [:"woman-girl"]),
      self.new("\u{1F469 200D 1F4BB}", [:"female-technologist"]),
      self.new("\u{1F469 200D 1F4BC}", [:"female-office-worker"]),
      self.new("\u{1F469 200D 1F527}", [:"female-mechanic"]),
      self.new("\u{1F469 200D 1F52C}", [:"female-scientist"]),
      self.new("\u{1F469 200D 1F680}", [:"female-astronaut"]),
      self.new("\u{1F469 200D 1F692}", [:"female-firefighter"]),
      self.new("\u{1F469 200D 2695 FE0F}", [:"female-doctor"]),
      self.new("\u{1F469 200D 2696 FE0F}", [:"female-judge"]),
      self.new("\u{1F469 200D 2708 FE0F}", [:"female-pilot"]),
      self.new("\u{1F46A}", [:family]),
      self.new("\u{1F46A}", [:"man-woman-boy"]),
      self.new("\u{1F46B}", [:man_and_woman_holding_hands]),
      self.new("\u{1F46E 200D 2640 FE0F}", [:"female-police-officer"]),
      self.new("\u{1F46E 200D 2642 FE0F}", [:"male-police-officer"]),
      self.new("\u{1F46F 200D 2640 FE0F}", [:"woman-with-bunny-ears-partying"]),
      self.new("\u{1F46F 200D 2642 FE0F}", [:"man-with-bunny-ears-partying"]),
      self.new("\u{1F471 200D 2640 FE0F}", [:"blond-haired-woman"]),
      self.new("\u{1F471 200D 2642 FE0F}", [:"blond-haired-man"]),
      self.new("\u{1F473 200D 2640 FE0F}", [:"woman-wearing-turban"]),
      self.new("\u{1F473 200D 2642 FE0F}", [:"man-wearing-turban"]),
      self.new("\u{1F477 200D 2640 FE0F}", [:"female-construction-worker"]),
      self.new("\u{1F477 200D 2642 FE0F}", [:"male-construction-worker"]),
      self.new("\u{1F481 200D 2640 FE0F}", [:"woman-tipping-hand"]),
      self.new("\u{1F481 200D 2642 FE0F}", [:"man-tipping-hand"]),
      self.new("\u{1F482 200D 2640 FE0F}", [:"female-guard"]),
      self.new("\u{1F482 200D 2642 FE0F}", [:"male-guard"]),
      self.new("\u{1F486 200D 2640 FE0F}", [:"woman-getting-massage"]),
      self.new("\u{1F486 200D 2642 FE0F}", [:"man-getting-massage"]),
      self.new("\u{1F487 200D 2640 FE0F}", [:"woman-getting-haircut"]),
      self.new("\u{1F487 200D 2642 FE0F}", [:"man-getting-haircut"]),
      self.new("\u{1F4A4}", [:zzz]),
      self.new("\u{1F4D6}", [:open_book]),
      self.new("\u{1F4E1}", [:satellite_antenna]),
      self.new("\u{1F4E7}", [:"e-mail"]),
      self.new("\u{1F52A}", [:knife]),
      self.new("\u{1F575 FE0F 200D 2640 FE0F}", [:"female-detective"]),
      self.new("\u{1F575 FE0F 200D 2642 FE0F}", [:"male-detective"]),
      self.new("\u{1F57A}", [:man_dancing]),
      self.new("\u{1F595}", [:reversed_hand_with_middle_finger_extended]),
      self.new("\u{1F5A4}", [:black_heart]),
      self.new("\u{1F5E8 FE0F}", [:left_speech_bubble]),
      self.new("\u{1F645 200D 2640 FE0F}", [:"woman-gesturing-no"]),
      self.new("\u{1F645 200D 2642 FE0F}", [:"man-gesturing-no"]),
      self.new("\u{1F646 200D 2640 FE0F}", [:"woman-gesturing-ok"]),
      self.new("\u{1F646 200D 2642 FE0F}", [:"man-gesturing-ok"]),
      self.new("\u{1F647 200D 2640 FE0F}", [:"woman-bowing"]),
      self.new("\u{1F647 200D 2642 FE0F}", [:"man-bowing"]),
      self.new("\u{1F64B 200D 2640 FE0F}", [:"woman-raising-hand"]),
      self.new("\u{1F64B 200D 2642 FE0F}", [:"man-raising-hand"]),
      self.new("\u{1F64D 200D 2640 FE0F}", [:"woman-frowning"]),
      self.new("\u{1F64D 200D 2642 FE0F}", [:"man-frowning"]),
      self.new("\u{1F64E 200D 2640 FE0F}", [:"woman-pouting"]),
      self.new("\u{1F64E 200D 2642 FE0F}", [:"man-pouting"]),
      self.new("\u{1F6A3 200D 2640 FE0F}", [:"woman-rowing-boat"]),
      self.new("\u{1F6A3 200D 2642 FE0F}", [:"man-rowing-boat"]),
      self.new("\u{1F6B4 200D 2640 FE0F}", [:"woman-biking"]),
      self.new("\u{1F6B4 200D 2642 FE0F}", [:"man-biking"]),
      self.new("\u{1F6B5 200D 2640 FE0F}", [:"woman-mountain-biking"]),
      self.new("\u{1F6B5 200D 2642 FE0F}", [:"man-mountain-biking"]),
      self.new("\u{1F6B6 200D 2640 FE0F}", [:"woman-walking"]),
      self.new("\u{1F6B6 200D 2642 FE0F}", [:"man-walking"]),
      self.new("\u{1F6D1}", [:octagonal_sign]),
      self.new("\u{1F6D2}", [:shopping_trolley]),
      self.new("\u{1F6F4}", [:scooter]),
      self.new("\u{1F6F5}", [:motor_scooter]),
      self.new("\u{1F6F6}", [:canoe]),
      self.new("\u{1F6F7}", [:sled]),
      self.new("\u{1F6F8}", [:flying_saucer]),
      self.new("\u{1F918}", [:sign_of_the_horns]),
      self.new("\u{1F919}", [:call_me_hand]),
      self.new("\u{1F91A}", [:raised_back_of_hand]),
      self.new("\u{1F91B}", [:"left-facing_fist"]),
      self.new("\u{1F91C}", [:"right-facing_fist"]),
      self.new("\u{1F91E}", [:hand_with_index_and_middle_fingers_crossed]),
      self.new("\u{1F91F}", [:i_love_you_hand_sign]),
      self.new("\u{1F922}", [:nauseated_face]),
      self.new("\u{1F923}", [:rolling_on_the_floor_laughing]),
      self.new("\u{1F924}", [:drooling_face]),
      self.new("\u{1F925}", [:lying_face]),
      self.new("\u{1F926 200D 2640 FE0F}", [:"woman-facepalming"]),
      self.new("\u{1F926 200D 2642 FE0F}", [:"man-facepalming"]),
      self.new("\u{1F926}", [:face_palm]),
      self.new("\u{1F927}", [:sneezing_face]),
      self.new("\u{1F928}", [:face_with_one_eyebrow_raised]),
      self.new("\u{1F929}", [:grinning_face_with_star_eyes]),
      self.new("\u{1F92A}", [:grinning_face_with_one_large_and_one_small_eye]),
      self.new("\u{1F92B}", [:face_with_finger_covering_closed_lips]),
      self.new("\u{1F92C}", [:serious_face_with_symbols_covering_mouth]),
      self.new("\u{1F92D}", [:smiling_face_with_smiling_eyes_and_hand_covering_mouth]),
      self.new("\u{1F92E}", [:face_with_open_mouth_vomiting]),
      self.new("\u{1F92F}", [:shocked_face_with_exploding_head]),
      self.new("\u{1F930}", [:pregnant_woman]),
      self.new("\u{1F931}", [:"breast-feeding"]),
      self.new("\u{1F932}", [:palms_up_together]),
      self.new("\u{1F933}", [:selfie]),
      self.new("\u{1F934}", [:prince]),
      self.new("\u{1F935}", [:man_in_tuxedo]),
      self.new("\u{1F936}", [:mother_christmas]),
      self.new("\u{1F937 200D 2640 FE0F}", [:"woman-shrugging"]),
      self.new("\u{1F937 200D 2642 FE0F}", [:"man-shrugging"]),
      self.new("\u{1F937}", [:shrug]),
      self.new("\u{1F938 200D 2640 FE0F}", [:"woman-cartwheeling"]),
      self.new("\u{1F938 200D 2642 FE0F}", [:"man-cartwheeling"]),
      self.new("\u{1F938}", [:person_doing_cartwheel]),
      self.new("\u{1F939 200D 2640 FE0F}", [:"woman-juggling"]),
      self.new("\u{1F939 200D 2642 FE0F}", [:"man-juggling"]),
      self.new("\u{1F939}", [:juggling]),
      self.new("\u{1F93A}", [:fencer]),
      self.new("\u{1F93C 200D 2640 FE0F}", [:"woman-wrestling"]),
      self.new("\u{1F93C 200D 2642 FE0F}", [:"man-wrestling"]),
      self.new("\u{1F93C}", [:wrestlers]),
      self.new("\u{1F93D 200D 2640 FE0F}", [:"woman-playing-water-polo"]),
      self.new("\u{1F93D 200D 2642 FE0F}", [:"man-playing-water-polo"]),
      self.new("\u{1F93D}", [:water_polo]),
      self.new("\u{1F93E 200D 2640 FE0F}", [:"woman-playing-handball"]),
      self.new("\u{1F93E 200D 2642 FE0F}", [:"man-playing-handball"]),
      self.new("\u{1F93E}", [:handball]),
      self.new("\u{1F940}", [:wilted_flower]),
      self.new("\u{1F941}", [:drum_with_drumsticks]),
      self.new("\u{1F944}", [:spoon]),
      self.new("\u{1F945}", [:goal_net]),
      self.new("\u{1F947}", [:first_place_medal]),
      self.new("\u{1F948}", [:second_place_medal]),
      self.new("\u{1F949}", [:third_place_medal]),
      self.new("\u{1F94A}", [:boxing_glove]),
      self.new("\u{1F94B}", [:martial_arts_uniform]),
      self.new("\u{1F94C}", [:curling_stone]),
      self.new("\u{1F958}", [:shallow_pan_of_food]),
      self.new("\u{1F95F}", [:dumpling]),
      self.new("\u{1F960}", [:fortune_cookie]),
      self.new("\u{1F961}", [:takeout_box]),
      self.new("\u{1F962}", [:chopsticks]),
      self.new("\u{1F963}", [:bowl_with_spoon]),
      self.new("\u{1F964}", [:cup_with_straw]),
      self.new("\u{1F965}", [:coconut]),
      self.new("\u{1F966}", [:broccoli]),
      self.new("\u{1F967}", [:pie]),
      self.new("\u{1F968}", [:pretzel]),
      self.new("\u{1F969}", [:cut_of_meat]),
      self.new("\u{1F96A}", [:sandwich]),
      self.new("\u{1F96B}", [:canned_food]),
      self.new("\u{1F985}", [:eagle]),
      self.new("\u{1F986}", [:duck]),
      self.new("\u{1F987}", [:bat]),
      self.new("\u{1F988}", [:shark]),
      self.new("\u{1F989}", [:owl]),
      self.new("\u{1F98A}", [:fox_face]),
      self.new("\u{1F98B}", [:butterfly]),
      self.new("\u{1F98C}", [:deer]),
      self.new("\u{1F98D}", [:gorilla]),
      self.new("\u{1F98E}", [:lizard]),
      self.new("\u{1F98F}", [:rhinoceros]),
      self.new("\u{1F990}", [:shrimp]),
      self.new("\u{1F991}", [:squid]),
      self.new("\u{1F992}", [:giraffe_face]),
      self.new("\u{1F993}", [:zebra_face]),
      self.new("\u{1F994}", [:hedgehog]),
      self.new("\u{1F995}", [:sauropod]),
      self.new("\u{1F996}", [:"t-rex"]),
      self.new("\u{1F997}", [:cricket]),
      self.new("\u{1F9D0}", [:face_with_monocle]),
      self.new("\u{1F9D1}", [:adult]),
      self.new("\u{1F9D2}", [:child]),
      self.new("\u{1F9D3}", [:older_adult]),
      self.new("\u{1F9D4}", [:bearded_person]),
      self.new("\u{1F9D5}", [:person_with_headscarf]),
      self.new("\u{1F9D6 200D 2640 FE0F}", [:woman_in_steamy_room]),
      self.new("\u{1F9D6 200D 2642 FE0F}", [:man_in_steamy_room]),
      self.new("\u{1F9D6}", [:person_in_steamy_room]),
      self.new("\u{1F9D7 200D 2640 FE0F}", [:woman_climbing]),
      self.new("\u{1F9D7 200D 2642 FE0F}", [:man_climbing]),
      self.new("\u{1F9D7}", [:person_climbing]),
      self.new("\u{1F9D8 200D 2640 FE0F}", [:woman_in_lotus_position]),
      self.new("\u{1F9D8 200D 2642 FE0F}", [:man_in_lotus_position]),
      self.new("\u{1F9D8}", [:person_in_lotus_position]),
      self.new("\u{1F9D9 200D 2640 FE0F}", [:female_mage]),
      self.new("\u{1F9D9 200D 2642 FE0F}", [:male_mage]),
      self.new("\u{1F9D9}", [:mage]),
      self.new("\u{1F9DA 200D 2640 FE0F}", [:female_fairy]),
      self.new("\u{1F9DA 200D 2642 FE0F}", [:male_fairy]),
      self.new("\u{1F9DA}", [:fairy]),
      self.new("\u{1F9DB 200D 2640 FE0F}", [:female_vampire]),
      self.new("\u{1F9DB 200D 2642 FE0F}", [:male_vampire]),
      self.new("\u{1F9DB}", [:vampire]),
      self.new("\u{1F9DC 200D 2640 FE0F}", [:mermaid]),
      self.new("\u{1F9DC 200D 2642 FE0F}", [:merman]),
      self.new("\u{1F9DC}", [:merperson]),
      self.new("\u{1F9DD 200D 2640 FE0F}", [:female_elf]),
      self.new("\u{1F9DD 200D 2642 FE0F}", [:male_elf]),
      self.new("\u{1F9DD}", [:elf]),
      self.new("\u{1F9DE 200D 2640 FE0F}", [:female_genie]),
      self.new("\u{1F9DE 200D 2642 FE0F}", [:male_genie]),
      self.new("\u{1F9DE}", [:genie]),
      self.new("\u{1F9DF 200D 2640 FE0F}", [:female_zombie]),
      self.new("\u{1F9DF 200D 2642 FE0F}", [:male_zombie]),
      self.new("\u{1F9DF}", [:zombie]),
      self.new("\u{1F9E0}", [:brain]),
      self.new("\u{1F9E1}", [:orange_heart]),
      self.new("\u{1F9E2}", [:billed_cap]),
      self.new("\u{1F9E3}", [:scarf]),
      self.new("\u{1F9E4}", [:gloves]),
      self.new("\u{1F9E5}", [:coat]),
      self.new("\u{1F9E6}", [:socks]),
      self.new("\u{23CF FE0F}", [:eject]),
      self.new("\u{2614}", [:umbrella_with_rain_drops]),
      self.new("\u{2640 FE0F}", [:female_sign]),
      self.new("\u{2642 FE0F}", [:male_sign]),
      self.new("\u{2695 FE0F}", [:staff_of_aesculapius]),
      self.new("\u{26F9 FE0F 200D 2640 FE0F}", [:"woman-bouncing-ball"]),
      self.new("\u{26F9 FE0F 200D 2642 FE0F}", [:"man-bouncing-ball"]),
      self.new("\u{270F FE0F}", [:pencil2]),
      self.new("\u{2757}", [:heavy_exclamation_mark]),
      self.new("\u{1FAE0}", [:melting_face], "MELTING FACE"),
      self.new("\u{1F970}", [:smiling_face_with_hearts], "SMILING FACE WITH HEARTS"),
      self.new("\u{1F972}", [:smiling_face_with_tear], "SMILING FACE WITH TEAR"),
      self.new("\u{1FAE2}", [:face_with_open_eyes_and_hand_over_mouth], "FACE WITH OPEN EYES AND HAND OVER MOUTH"),
      self.new("\u{1FAE3}", [:face_with_peeking_eye], "FACE WITH PEEKING EYE"),
      self.new("\u{1FAE1}", [:saluting_face], "SALUTING FACE"),
      self.new("\u{1FAE5}", [:dotted_line_face], "DOTTED LINE FACE"),
      self.new("\u{1F975}", [:hot_face], "HOT FACE"),
      self.new("\u{1F976}", [:cold_face], "COLD FACE"),
      self.new("\u{1F974}", [:woozy_face], "WOOZY FACE"),
      self.new("\u{1F973}", [:partying_face], "PARTYING FACE"),
      self.new("\u{1F978}", [:disguised_face], "DISGUISED FACE"),
      self.new("\u{1FAE4}", [:face_with_diagonal_mouth], "FACE WITH DIAGONAL MOUTH"),
      self.new("\u{2639}", [:frowning_face], "FROWNING FACE"),
      self.new("\u{1F97A}", [:pleading_face], "PLEADING FACE"),
      self.new("\u{1F979}", [:face_holding_back_tears], "FACE HOLDING BACK TEARS"),
      self.new("\u{1F971}", [:yawning_face], "YAWNING FACE"),
      self.new("\u{1F47E}", [:alien_monster], "ALIEN MONSTER"),
      self.new("\u{1F49F}", [:heart_decoration], "HEART DECORATION"),
      self.new("\u{2764 FE0F 200D 1FA79}", [:mending_heart], "MENDING HEART"),
      self.new("\u{1F90E}", [:brown_heart], "BROWN HEART"),
      self.new("\u{1F90D}", [:white_heart], "WHITE HEART"),
      self.new("\u{1F4AF}", [:hundred_points], "HUNDRED POINTS"),
      self.new("\u{1FAF1}", [:rightwards_hand], "RIGHTWARDS HAND"),
      self.new("\u{1FAF2}", [:leftwards_hand], "LEFTWARDS HAND"),
      self.new("\u{1FAF3}", [:palm_down_hand], "PALM DOWN HAND"),
      self.new("\u{1FAF4}", [:palm_up_hand], "PALM UP HAND"),
      self.new("\u{1F90C}", [:pinched_fingers], "PINCHED FINGERS"),
      self.new("\u{1F90F}", [:pinching_hand], "PINCHING HAND"),
      self.new("\u{1FAF0}", [:hand_with_index_finger_and_thumb_crossed], "HAND WITH INDEX FINGER AND THUMB CROSSED"),
      self.new("\u{1FAF5}", [:index_pointing_at_the_viewer], "INDEX POINTING AT THE VIEWER"),
      self.new("\u{1FAF6}", [:heart_hands], "HEART HANDS"),
      self.new("\u{270D}", [:writing_hand], "WRITING HAND"),
      self.new("\u{1F9BE}", [:mechanical_arm], "MECHANICAL ARM"),
      self.new("\u{1F9BF}", [:mechanical_leg], "MECHANICAL LEG"),
      self.new("\u{1F9B5}", [:leg], "LEG"),
      self.new("\u{1F9B6}", [:foot], "FOOT"),
      self.new("\u{1F9BB}", [:ear_with_hearing_aid], "EAR WITH HEARING AID"),
      self.new("\u{1FAC0}", [:anatomical_heart], "ANATOMICAL HEART"),
      self.new("\u{1FAC1}", [:lungs], "LUNGS"),
      self.new("\u{1F9B7}", [:tooth], "TOOTH"),
      self.new("\u{1F9B4}", [:bone], "BONE"),
      self.new("\u{1FAE6}", [:biting_lip], "BITING LIP"),
      self.new("\u{1F468 200D 1F9B0}", [:man_red_hair], "MAN RED HAIR"),
      self.new("\u{1F468 200D 1F9B1}", [:man_curly_hair], "MAN CURLY HAIR"),
      self.new("\u{1F468 200D 1F9B3}", [:man_white_hair], "MAN WHITE HAIR"),
      self.new("\u{1F468 200D 1F9B2}", [:man_bald], "MAN BALD"),
      self.new("\u{1F469 200D 1F9B0}", [:woman_red_hair], "WOMAN RED HAIR"),
      self.new("\u{1F9D1 200D 1F9B0}", [:person_red_hair], "PERSON RED HAIR"),
      self.new("\u{1F469 200D 1F9B1}", [:woman_curly_hair], "WOMAN CURLY HAIR"),
      self.new("\u{1F9D1 200D 1F9B1}", [:person_curly_hair], "PERSON CURLY HAIR"),
      self.new("\u{1F469 200D 1F9B3}", [:woman_white_hair], "WOMAN WHITE HAIR"),
      self.new("\u{1F9D1 200D 1F9B3}", [:person_white_hair], "PERSON WHITE HAIR"),
      self.new("\u{1F469 200D 1F9B2}", [:woman_bald], "WOMAN BALD"),
      self.new("\u{1F9D1 200D 1F9B2}", [:person_bald], "PERSON BALD"),
      self.new("\u{1F9CF}", [:deaf_person], "DEAF PERSON"),
      self.new("\u{1F977}", [:ninja], "NINJA"),
      self.new("\u{1FAC5}", [:person_with_crown], "PERSON WITH CROWN"),
      self.new("\u{1FAC3}", [:pregnant_man], "PREGNANT MAN"),
      self.new("\u{1FAC4}", [:pregnant_person], "PREGNANT PERSON"),
      self.new("\u{1F469 200D 1F37C}", [:woman_feeding_baby], "WOMAN FEEDING BABY"),
      self.new("\u{1F468 200D 1F37C}", [:man_feeding_baby], "MAN FEEDING BABY"),
      self.new("\u{1F9D1 200D 1F37C}", [:person_feeding_baby], "PERSON FEEDING BABY"),
      self.new("\u{1F9D1 200D 1F384}", [:mx_claus], "MX CLAUS"),
      self.new("\u{1F9B8}", [:superhero], "SUPERHERO"),
      self.new("\u{1F9B9}", [:supervillain], "SUPERVILLAIN"),
      self.new("\u{1F9CC}", [:troll], "TROLL"),
      self.new("\u{1F9CD}", [:person_standing], "PERSON STANDING"),
      self.new("\u{1F9CE}", [:person_kneeling], "PERSON KNEELING"),
      self.new("\u{1F9D1 200D 1F9AF}", [:person_with_white_cane], "PERSON WITH WHITE CANE"),
      self.new("\u{1F468 200D 1F9AF}", [:man_with_white_cane], "MAN WITH WHITE CANE"),
      self.new("\u{1F469 200D 1F9AF}", [:woman_with_white_cane], "WOMAN WITH WHITE CANE"),
      self.new("\u{1F9D1 200D 1F9BC}", [:person_in_motorized_wheelchair], "PERSON IN MOTORIZED WHEELCHAIR"),
      self.new("\u{1F468 200D 1F9BC}", [:man_in_motorized_wheelchair], "MAN IN MOTORIZED WHEELCHAIR"),
      self.new("\u{1F469 200D 1F9BC}", [:woman_in_motorized_wheelchair], "WOMAN IN MOTORIZED WHEELCHAIR"),
      self.new("\u{1F9D1 200D 1F9BD}", [:person_in_manual_wheelchair], "PERSON IN MANUAL WHEELCHAIR"),
      self.new("\u{1F468 200D 1F9BD}", [:man_in_manual_wheelchair], "MAN IN MANUAL WHEELCHAIR"),
      self.new("\u{1F469 200D 1F9BD}", [:woman_in_manual_wheelchair], "WOMAN IN MANUAL WHEELCHAIR"),
      self.new("\u{1F3C7}", [:horse_racing], "HORSE RACING"),
      self.new("\u{1F3C2}", [:snowboarder], "SNOWBOARDER"),
      self.new("\u{1F3C4}", [:person_surfing], "PERSON SURFING"),
      self.new("\u{1F6A3}", [:person_rowing_boat], "PERSON ROWING BOAT"),
      self.new("\u{1F3CA}", [:person_swimming], "PERSON SWIMMING"),
      self.new("\u{1F6B4}", [:person_biking], "PERSON BIKING"),
      self.new("\u{1F6B5}", [:person_mountain_biking], "PERSON MOUNTAIN BIKING"),
      self.new("\u{1F6C0}", [:person_taking_bath], "PERSON TAKING BATH"),
      self.new("\u{1F6CC}", [:person_in_bed], "PERSON IN BED"),
      self.new("\u{1FAC2}", [:people_hugging], "PEOPLE HUGGING"),
      self.new("\u{1F9B0}", [:red_hair], "RED HAIR"),
      self.new("\u{1F9B1}", [:curly_hair], "CURLY HAIR"),
      self.new("\u{1F9B3}", [:white_hair], "WHITE HAIR"),
      self.new("\u{1F9B2}", [:bald], "BALD"),
      self.new("\u{1F9A7}", [:orangutan], "ORANGUTAN"),
      self.new("\u{1F9AE}", [:guide_dog], "GUIDE DOG"),
      self.new("\u{1F415 200D 1F9BA}", [:service_dog], "SERVICE DOG"),
      self.new("\u{1F99D}", [:raccoon], "RACCOON"),
      self.new("\u{1F408 200D 2B1B}", [:black_cat], "BLACK CAT"),
      self.new("\u{1F9AC}", [:bison], "BISON"),
      self.new("\u{1F999}", [:llama], "LLAMA"),
      self.new("\u{1F9A3}", [:mammoth], "MAMMOTH"),
      self.new("\u{1F99B}", [:hippopotamus], "HIPPOPOTAMUS"),
      self.new("\u{1F9AB}", [:beaver], "BEAVER"),
      self.new("\u{1F9A5}", [:sloth], "SLOTH"),
      self.new("\u{1F9A6}", [:otter], "OTTER"),
      self.new("\u{1F9A8}", [:skunk], "SKUNK"),
      self.new("\u{1F998}", [:kangaroo], "KANGAROO"),
      self.new("\u{1F9A1}", [:badger], "BADGER"),
      self.new("\u{1F54A}", [:dove], "DOVE"),
      self.new("\u{1F9A2}", [:swan], "SWAN"),
      self.new("\u{1F9A4}", [:dodo], "DODO"),
      self.new("\u{1FAB6}", [:feather], "FEATHER"),
      self.new("\u{1F9A9}", [:flamingo], "FLAMINGO"),
      self.new("\u{1F99A}", [:peacock], "PEACOCK"),
      self.new("\u{1F99C}", [:parrot], "PARROT"),
      self.new("\u{1F9AD}", [:seal], "SEAL"),
      self.new("\u{1FAB8}", [:coral], "CORAL"),
      self.new("\u{1FAB2}", [:beetle], "BEETLE"),
      self.new("\u{1FAB3}", [:cockroach], "COCKROACH"),
      self.new("\u{1F577}", [:spider], "SPIDER"),
      self.new("\u{1F578}", [:spider_web], "SPIDER WEB"),
      self.new("\u{1F99F}", [:mosquito], "MOSQUITO"),
      self.new("\u{1FAB0}", [:fly], "FLY"),
      self.new("\u{1FAB1}", [:worm], "WORM"),
      self.new("\u{1F9A0}", [:microbe], "MICROBE"),
      self.new("\u{1F4AE}", [:white_flower], "WHITE FLOWER"),
      self.new("\u{1FAB7}", [:lotus], "LOTUS"),
      self.new("\u{1FAB4}", [:potted_plant], "POTTED PLANT"),
      self.new("\u{1FAB9}", [:empty_nest], "EMPTY NEST"),
      self.new("\u{1FABA}", [:nest_with_eggs], "NEST WITH EGGS"),
      self.new("\u{1F347}", [:grapes], "GRAPES"),
      self.new("\u{1F348}", [:melon], "MELON"),
      self.new("\u{1F349}", [:watermelon], "WATERMELON"),
      self.new("\u{1F34A}", [:tangerine], "TANGERINE"),
      self.new("\u{1F34B}", [:lemon], "LEMON"),
      self.new("\u{1F34C}", [:banana], "BANANA"),
      self.new("\u{1F34D}", [:pineapple], "PINEAPPLE"),
      self.new("\u{1F34F}", [:green_apple], "GREEN APPLE"),
      self.new("\u{1F350}", [:pear], "PEAR"),
      self.new("\u{1F351}", [:peach], "PEACH"),
      self.new("\u{1F352}", [:cherries], "CHERRIES"),
      self.new("\u{1F353}", [:strawberry], "STRAWBERRY"),
      self.new("\u{1FAD0}", [:blueberries], "BLUEBERRIES"),
      self.new("\u{1F345}", [:tomato], "TOMATO"),
      self.new("\u{1FAD2}", [:olive], "OLIVE"),
      self.new("\u{1F346}", [:eggplant], "EGGPLANT"),
      self.new("\u{1F33D}", [:ear_of_corn], "EAR OF CORN"),
      self.new("\u{1F336}", [:hot_pepper], "HOT PEPPER"),
      self.new("\u{1FAD1}", [:bell_pepper], "BELL PEPPER"),
      self.new("\u{1F9C4}", [:garlic], "GARLIC"),
      self.new("\u{1F9C5}", [:onion], "ONION"),
      self.new("\u{1FAD8}", [:beans], "BEANS"),
      self.new("\u{1F35E}", [:bread], "BREAD"),
      self.new("\u{1FAD3}", [:flatbread], "FLATBREAD"),
      self.new("\u{1F9C7}", [:waffle], "WAFFLE"),
      self.new("\u{1F9C0}", [:cheese_wedge], "CHEESE WEDGE"),
      self.new("\u{1F356}", [:meat_on_bone], "MEAT ON BONE"),
      self.new("\u{1F357}", [:poultry_leg], "POULTRY LEG"),
      self.new("\u{1F354}", [:hamburger], "HAMBURGER"),
      self.new("\u{1F35F}", [:french_fries], "FRENCH FRIES"),
      self.new("\u{1F355}", [:pizza], "PIZZA"),
      self.new("\u{1F32D}", [:hot_dog], "HOT DOG"),
      self.new("\u{1F32E}", [:taco], "TACO"),
      self.new("\u{1F32F}", [:burrito], "BURRITO"),
      self.new("\u{1FAD4}", [:tamale], "TAMALE"),
      self.new("\u{1F9C6}", [:falafel], "FALAFEL"),
      self.new("\u{1F372}", [:pot_of_food], "POT OF FOOD"),
      self.new("\u{1FAD5}", [:fondue], "FONDUE"),
      self.new("\u{1F37F}", [:popcorn], "POPCORN"),
      self.new("\u{1F9C8}", [:butter], "BUTTER"),
      self.new("\u{1F9C2}", [:salt], "SALT"),
      self.new("\u{1F371}", [:bento_box], "BENTO BOX"),
      self.new("\u{1F358}", [:rice_cracker], "RICE CRACKER"),
      self.new("\u{1F359}", [:rice_ball], "RICE BALL"),
      self.new("\u{1F35A}", [:cooked_rice], "COOKED RICE"),
      self.new("\u{1F35B}", [:curry_rice], "CURRY RICE"),
      self.new("\u{1F35C}", [:steaming_bowl], "STEAMING BOWL"),
      self.new("\u{1F35D}", [:spaghetti], "SPAGHETTI"),
      self.new("\u{1F360}", [:roasted_sweet_potato], "ROASTED SWEET POTATO"),
      self.new("\u{1F362}", [:oden], "ODEN"),
      self.new("\u{1F363}", [:sushi], "SUSHI"),
      self.new("\u{1F364}", [:fried_shrimp], "FRIED SHRIMP"),
      self.new("\u{1F365}", [:fish_cake_with_swirl], "FISH CAKE WITH SWIRL"),
      self.new("\u{1F361}", [:dango], "DANGO"),
      self.new("\u{1F9AA}", [:oyster], "OYSTER"),
      self.new("\u{1F366}", [:soft_ice_cream], "SOFT ICE CREAM"),
      self.new("\u{1F367}", [:shaved_ice], "SHAVED ICE"),
      self.new("\u{1F368}", [:ice_cream], "ICE CREAM"),
      self.new("\u{1F369}", [:doughnut], "DOUGHNUT"),
      self.new("\u{1F36A}", [:cookie], "COOKIE"),
      self.new("\u{1F382}", [:birthday_cake], "BIRTHDAY CAKE"),
      self.new("\u{1F370}", [:shortcake], "SHORTCAKE"),
      self.new("\u{1F36B}", [:chocolate_bar], "CHOCOLATE BAR"),
      self.new("\u{1F36C}", [:candy], "CANDY"),
      self.new("\u{1F36D}", [:lollipop], "LOLLIPOP"),
      self.new("\u{1F36E}", [:custard], "CUSTARD"),
      self.new("\u{1F36F}", [:honey_pot], "HONEY POT"),
      self.new("\u{1F37C}", [:baby_bottle], "BABY BOTTLE"),
      self.new("\u{1FAD6}", [:teapot], "TEAPOT"),
      self.new("\u{1F375}", [:teacup_without_handle], "TEACUP WITHOUT HANDLE"),
      self.new("\u{1F376}", [:sake], "SAKE"),
      self.new("\u{1F37E}", [:bottle_with_popping_cork], "BOTTLE WITH POPPING CORK"),
      self.new("\u{1F377}", [:wine_glass], "WINE GLASS"),
      self.new("\u{1F378}", [:cocktail_glass], "COCKTAIL GLASS"),
      self.new("\u{1F379}", [:tropical_drink], "TROPICAL DRINK"),
      self.new("\u{1F37A}", [:beer_mug], "BEER MUG"),
      self.new("\u{1F37B}", [:clinking_beer_mugs], "CLINKING BEER MUGS"),
      self.new("\u{1FAD7}", [:pouring_liquid], "POURING LIQUID"),
      self.new("\u{1F9CB}", [:bubble_tea], "BUBBLE TEA"),
      self.new("\u{1F9C3}", [:beverage_box], "BEVERAGE BOX"),
      self.new("\u{1F9C9}", [:mate], "MATE"),
      self.new("\u{1F9CA}", [:ice], "ICE"),
      self.new("\u{1F37D}", [:fork_and_knife_with_plate], "FORK AND KNIFE WITH PLATE"),
      self.new("\u{1F374}", [:fork_and_knife], "FORK AND KNIFE"),
      self.new("\u{1FAD9}", [:jar], "JAR"),
      self.new("\u{1F3FA}", [:amphora], "AMPHORA"),
      self.new("\u{1F5FA}", [:world_map], "WORLD MAP"),
      self.new("\u{1F5FE}", [:map_of_Japan], "MAP OF JAPAN"),
      self.new("\u{1F9ED}", [:compass], "COMPASS"),
      self.new("\u{1F3D4}", [:"snow-capped-mountain"], "SNOW CAPPED MOUNTAIN"),
      self.new("\u{26F0}", [:mountain], "MOUNTAIN"),
      self.new("\u{1F5FB}", [:mount_fuji], "MOUNT FUJI"),
      self.new("\u{1F3D5}", [:camping], "CAMPING"),
      self.new("\u{1F3D6}", [:beach_with_umbrella], "BEACH WITH UMBRELLA"),
      self.new("\u{1F3DC}", [:desert], "DESERT"),
      self.new("\u{1F3DD}", [:desert_island], "DESERT ISLAND"),
      self.new("\u{1F3DE}", [:national_park], "NATIONAL PARK"),
      self.new("\u{1F3DF}", [:stadium], "STADIUM"),
      self.new("\u{1F3DB}", [:classical_building], "CLASSICAL BUILDING"),
      self.new("\u{1F3D7}", [:building_construction], "BUILDING CONSTRUCTION"),
      self.new("\u{1F9F1}", [:brick], "BRICK"),
      self.new("\u{1FAA8}", [:rock], "ROCK"),
      self.new("\u{1FAB5}", [:wood], "WOOD"),
      self.new("\u{1F6D6}", [:hut], "HUT"),
      self.new("\u{1F3D8}", [:houses], "HOUSES"),
      self.new("\u{1F3DA}", [:derelict_house], "DERELICT HOUSE"),
      self.new("\u{1F3E0}", [:house], "HOUSE"),
      self.new("\u{1F3E1}", [:house_with_garden], "HOUSE WITH GARDEN"),
      self.new("\u{1F3E2}", [:office_building], "OFFICE BUILDING"),
      self.new("\u{1F3E3}", [:Japanese_post_office], "JAPANESE POST OFFICE"),
      self.new("\u{1F3E4}", [:post_office], "POST OFFICE"),
      self.new("\u{1F3E5}", [:hospital], "HOSPITAL"),
      self.new("\u{1F3E6}", [:bank], "BANK"),
      self.new("\u{1F3E8}", [:hotel], "HOTEL"),
      self.new("\u{1F3E9}", [:love_hotel], "LOVE HOTEL"),
      self.new("\u{1F3EA}", [:convenience_store], "CONVENIENCE STORE"),
      self.new("\u{1F3EB}", [:school], "SCHOOL"),
      self.new("\u{1F3EC}", [:department_store], "DEPARTMENT STORE"),
      self.new("\u{1F3ED}", [:factory], "FACTORY"),
      self.new("\u{1F3EF}", [:Japanese_castle], "JAPANESE CASTLE"),
      self.new("\u{1F3F0}", [:castle], "CASTLE"),
      self.new("\u{1F492}", [:wedding], "WEDDING"),
      self.new("\u{1F5FC}", [:Tokyo_tower], "TOKYO TOWER"),
      self.new("\u{1F5FD}", [:Statue_of_Liberty], "STATUE OF LIBERTY"),
      self.new("\u{26EA}", [:church], "CHURCH"),
      self.new("\u{1F54C}", [:mosque], "MOSQUE"),
      self.new("\u{1F6D5}", [:hindu_temple], "HINDU TEMPLE"),
      self.new("\u{1F54D}", [:synagogue], "SYNAGOGUE"),
      self.new("\u{1F54B}", [:kaaba], "KAABA"),
      self.new("\u{26F2}", [:fountain], "FOUNTAIN"),
      self.new("\u{26FA}", [:tent], "TENT"),
      self.new("\u{1F303}", [:night_with_stars], "NIGHT WITH STARS"),
      self.new("\u{1F3D9}", [:cityscape], "CITYSCAPE"),
      self.new("\u{1F304}", [:sunrise_over_mountains], "SUNRISE OVER MOUNTAINS"),
      self.new("\u{1F305}", [:sunrise], "SUNRISE"),
      self.new("\u{1F306}", [:cityscape_at_dusk], "CITYSCAPE AT DUSK"),
      self.new("\u{1F307}", [:sunset], "SUNSET"),
      self.new("\u{1F309}", [:bridge_at_night], "BRIDGE AT NIGHT"),
      self.new("\u{1F3A0}", [:carousel_horse], "CAROUSEL HORSE"),
      self.new("\u{1F6DD}", [:playground_slide], "PLAYGROUND SLIDE"),
      self.new("\u{1F3A1}", [:ferris_wheel], "FERRIS WHEEL"),
      self.new("\u{1F3A2}", [:roller_coaster], "ROLLER COASTER"),
      self.new("\u{1F488}", [:barber_pole], "BARBER POLE"),
      self.new("\u{1F3AA}", [:circus_tent], "CIRCUS TENT"),
      self.new("\u{1F682}", [:locomotive], "LOCOMOTIVE"),
      self.new("\u{1F683}", [:railway_car], "RAILWAY CAR"),
      self.new("\u{1F684}", [:"high-speed-train"], "HIGH SPEED TRAIN"),
      self.new("\u{1F685}", [:bullet_train], "BULLET TRAIN"),
      self.new("\u{1F686}", [:train], "TRAIN"),
      self.new("\u{1F687}", [:metro], "METRO"),
      self.new("\u{1F688}", [:light_rail], "LIGHT RAIL"),
      self.new("\u{1F689}", [:station], "STATION"),
      self.new("\u{1F68A}", [:tram], "TRAM"),
      self.new("\u{1F69D}", [:monorail], "MONORAIL"),
      self.new("\u{1F69E}", [:mountain_railway], "MOUNTAIN RAILWAY"),
      self.new("\u{1F68B}", [:tram_car], "TRAM CAR"),
      self.new("\u{1F68C}", [:bus], "BUS"),
      self.new("\u{1F68D}", [:oncoming_bus], "ONCOMING BUS"),
      self.new("\u{1F68E}", [:trolleybus], "TROLLEYBUS"),
      self.new("\u{1F690}", [:minibus], "MINIBUS"),
      self.new("\u{1F691}", [:ambulance], "AMBULANCE"),
      self.new("\u{1F692}", [:fire_engine], "FIRE ENGINE"),
      self.new("\u{1F693}", [:police_car], "POLICE CAR"),
      self.new("\u{1F694}", [:oncoming_police_car], "ONCOMING POLICE CAR"),
      self.new("\u{1F695}", [:taxi], "TAXI"),
      self.new("\u{1F696}", [:oncoming_taxi], "ONCOMING TAXI"),
      self.new("\u{1F697}", [:automobile], "AUTOMOBILE"),
      self.new("\u{1F698}", [:oncoming_automobile], "ONCOMING AUTOMOBILE"),
      self.new("\u{1F699}", [:sport_utility_vehicle], "SPORT UTILITY VEHICLE"),
      self.new("\u{1F6FB}", [:pickup_truck], "PICKUP TRUCK"),
      self.new("\u{1F69A}", [:delivery_truck], "DELIVERY TRUCK"),
      self.new("\u{1F69B}", [:articulated_lorry], "ARTICULATED LORRY"),
      self.new("\u{1F69C}", [:tractor], "TRACTOR"),
      self.new("\u{1F3CE}", [:racing_car], "RACING CAR"),
      self.new("\u{1F3CD}", [:motorcycle], "MOTORCYCLE"),
      self.new("\u{1F9BD}", [:manual_wheelchair], "MANUAL WHEELCHAIR"),
      self.new("\u{1F9BC}", [:motorized_wheelchair], "MOTORIZED WHEELCHAIR"),
      self.new("\u{1F6FA}", [:auto_rickshaw], "AUTO RICKSHAW"),
      self.new("\u{1F6B2}", [:bicycle], "BICYCLE"),
      self.new("\u{1F6F9}", [:skateboard], "SKATEBOARD"),
      self.new("\u{1F6FC}", [:roller_skate], "ROLLER SKATE"),
      self.new("\u{1F68F}", [:bus_stop], "BUS STOP"),
      self.new("\u{1F6E3}", [:motorway], "MOTORWAY"),
      self.new("\u{1F6E4}", [:railway_track], "RAILWAY TRACK"),
      self.new("\u{1F6E2}", [:oil_drum], "OIL DRUM"),
      self.new("\u{26FD}", [:fuel_pump], "FUEL PUMP"),
      self.new("\u{1F6DE}", [:wheel], "WHEEL"),
      self.new("\u{1F6A8}", [:police_car_light], "POLICE CAR LIGHT"),
      self.new("\u{1F6A5}", [:horizontal_traffic_light], "HORIZONTAL TRAFFIC LIGHT"),
      self.new("\u{1F6A6}", [:vertical_traffic_light], "VERTICAL TRAFFIC LIGHT"),
      self.new("\u{1F6A7}", [:construction], "CONSTRUCTION"),
      self.new("\u{1F6DF}", [:ring_buoy], "RING BUOY"),
      self.new("\u{26F5}", [:sailboat], "SAILBOAT"),
      self.new("\u{1F6A4}", [:speedboat], "SPEEDBOAT"),
      self.new("\u{1F6F3}", [:passenger_ship], "PASSENGER SHIP"),
      self.new("\u{1F6E5}", [:motor_boat], "MOTOR BOAT"),
      self.new("\u{1F6A2}", [:ship], "SHIP"),
      self.new("\u{1F6E9}", [:small_airplane], "SMALL AIRPLANE"),
      self.new("\u{1F6EB}", [:airplane_departure], "AIRPLANE DEPARTURE"),
      self.new("\u{1F6EC}", [:airplane_arrival], "AIRPLANE ARRIVAL"),
      self.new("\u{1FA82}", [:parachute], "PARACHUTE"),
      self.new("\u{1F4BA}", [:seat], "SEAT"),
      self.new("\u{1F681}", [:helicopter], "HELICOPTER"),
      self.new("\u{1F69F}", [:suspension_railway], "SUSPENSION RAILWAY"),
      self.new("\u{1F6A0}", [:mountain_cableway], "MOUNTAIN CABLEWAY"),
      self.new("\u{1F6A1}", [:aerial_tramway], "AERIAL TRAMWAY"),
      self.new("\u{1F6F0}", [:satellite], "SATELLITE"),
      self.new("\u{1F680}", [:rocket], "ROCKET"),
      self.new("\u{1F6CE}", [:bellhop_bell], "BELLHOP BELL"),
      self.new("\u{1F9F3}", [:luggage], "LUGGAGE"),
      self.new("\u{231B}", [:hourglass_done], "HOURGLASS DONE"),
      self.new("\u{23F3}", [:hourglass_not_done], "HOURGLASS NOT DONE"),
      self.new("\u{231A}", [:watch], "WATCH"),
      self.new("\u{23F0}", [:alarm_clock], "ALARM CLOCK"),
      self.new("\u{23F1}", [:stopwatch], "STOPWATCH"),
      self.new("\u{23F2}", [:timer_clock], "TIMER CLOCK"),
      self.new("\u{1F570}", [:mantelpiece_clock], "MANTELPIECE CLOCK"),
      self.new("\u{1F321}", [:thermometer], "THERMOMETER"),
      self.new("\u{1FA90}", [:ringed_planet], "RINGED PLANET"),
      self.new("\u{26C8}",  [:cloud_with_lightning_and_rain], "CLOUD WITH LIGHTNING AND RAIN"),
      self.new("\u{1F308}", [:rainbow], "RAINBOW"),
      self.new("\u{1F302}", [:closed_umbrella], "CLOSED UMBRELLA"),
      self.new("\u{2602}",  [:umbrella], "UMBRELLA"),
      self.new("\u{26F1}",  [:umbrella_on_ground], "UMBRELLA ON GROUND"),
      self.new("\u{1F384}", [:Christmas_tree], "CHRISTMAS TREE"),
      self.new("\u{1F9E8}", [:firecracker], "FIRECRACKER"),
      self.new("\u{1F388}", [:balloon], "BALLOON"),
      self.new("\u{1F389}", [:party_popper], "PARTY POPPER"),
      self.new("\u{1F38A}", [:confetti_ball], "CONFETTI BALL"),
      self.new("\u{1F38B}", [:tanabata_tree], "TANABATA TREE"),
      self.new("\u{1F9E7}", [:red_envelope], "RED ENVELOPE"),
      self.new("\u{1F380}", [:ribbon], "RIBBON"),
      self.new("\u{1F381}", [:wrapped_gift], "WRAPPED GIFT"),
      self.new("\u{1F397}", [:reminder_ribbon], "REMINDER RIBBON"),
      self.new("\u{1F39F}", [:admission_tickets], "ADMISSION TICKETS"),
      self.new("\u{1F3AB}", [:ticket], "TICKET"),
      self.new("\u{1F396}", [:military_medal], "MILITARY MEDAL"),
      self.new("\u{1F3C6}", [:trophy], "TROPHY"),
      self.new("\u{1F3C5}", [:sports_medal], "SPORTS MEDAL"),
      self.new("\u{26BD}",  [:soccer_ball], "SOCCER BALL"),
      self.new("\u{26BE}",  [:baseball], "BASEBALL"),
      self.new("\u{1F94E}", [:softball], "SOFTBALL"),
      self.new("\u{1F3C0}", [:basketball], "BASKETBALL"),
      self.new("\u{1F3D0}", [:volleyball], "VOLLEYBALL"),
      self.new("\u{1F3C8}", [:american_football], "AMERICAN FOOTBALL"),
      self.new("\u{1F3C9}", [:rugby_football], "RUGBY FOOTBALL"),
      self.new("\u{1F3BE}", [:tennis], "TENNIS"),
      self.new("\u{1F94F}", [:flying_disc], "FLYING DISC"),
      self.new("\u{1F3B3}", [:bowling], "BOWLING"),
      self.new("\u{1F3CF}", [:cricket_game], "CRICKET GAME"),
      self.new("\u{1F3D1}", [:field_hockey], "FIELD HOCKEY"),
      self.new("\u{1F3D2}", [:ice_hockey], "ICE HOCKEY"),
      self.new("\u{1F94D}", [:lacrosse], "LACROSSE"),
      self.new("\u{1F3D3}", [:ping_pong], "PING PONG"),
      self.new("\u{1F3F8}", [:badminton], "BADMINTON"),
      self.new("\u{26F3}",  [:flag_in_hole], "FLAG IN HOLE"),
      self.new("\u{26F8}",  [:ice_skate], "ICE SKATE"),
      self.new("\u{1F3A3}", [:fishing_pole], "FISHING POLE"),
      self.new("\u{1F93F}", [:diving_mask], "DIVING MASK"),
      self.new("\u{1F3BD}", [:running_shirt], "RUNNING SHIRT"),
      self.new("\u{1F3BF}", [:skis], "SKIS"),
      self.new("\u{1F3AF}", [:bullseye], "BULLSEYE"),
      self.new("\u{1FA80}", [:"yo-yo"], "YO YO"),
      self.new("\u{1FA81}", [:kite], "KITE"),
      self.new("\u{1F52B}", [:water_pistol], "WATER PISTOL"),
      self.new("\u{1F3B1}", [:pool_8_ball], "POOL 8 BALL"),
      self.new("\u{1F52E}", [:crystal_ball], "CRYSTAL BALL"),
      self.new("\u{1FA84}", [:magic_wand], "MAGIC WAND"),
      self.new("\u{1F3AE}", [:video_game], "VIDEO GAME"),
      self.new("\u{1F579}", [:joystick], "JOYSTICK"),
      self.new("\u{1F3B0}", [:slot_machine], "SLOT MACHINE"),
      self.new("\u{1F3B2}", [:game_die], "GAME DIE"),
      self.new("\u{1F9E9}", [:puzzle_piece], "PUZZLE PIECE"),
      self.new("\u{1F9F8}", [:teddy_bear], "TEDDY BEAR"),
      self.new("\u{1FA85}", [:piñata], "PIÑATA"),
      self.new("\u{1FAA9}", [:mirror_ball], "MIRROR BALL"),
      self.new("\u{1FA86}", [:nesting_dolls], "NESTING DOLLS"),
      self.new("\u{265F}",  [:chess_pawn], "CHESS PAWN"),
      self.new("\u{1F0CF}", [:joker], "JOKER"),
      self.new("\u{1F004}", [:mahjong_red_dragon], "MAHJONG RED DRAGON"),
      self.new("\u{1F3B4}", [:flower_playing_cards], "FLOWER PLAYING CARDS"),
      self.new("\u{1F3AD}", [:performing_arts], "PERFORMING ARTS"),
      self.new("\u{1F5BC}", [:framed_picture], "FRAMED PICTURE"),
      self.new("\u{1F3A8}", [:artist_palette], "ARTIST PALETTE"),
      self.new("\u{1F9F5}", [:thread], "THREAD"),
      self.new("\u{1FAA1}", [:sewing_needle], "SEWING NEEDLE"),
      self.new("\u{1F9F6}", [:yarn], "YARN"),
      self.new("\u{1FAA2}", [:knot], "KNOT"),
      self.new("\u{1F453}", [:glasses], "GLASSES"),
      self.new("\u{1F97D}", [:goggles], "GOGGLES"),
      self.new("\u{1F97C}", [:lab_coat], "LAB COAT"),
      self.new("\u{1F9BA}", [:safety_vest], "SAFETY VEST"),
      self.new("\u{1F454}", [:necktie], "NECKTIE"),
      self.new("\u{1F455}", [:"t-shirt"], "T SHIRT"),
      self.new("\u{1F456}", [:jeans], "JEANS"),
      self.new("\u{1F457}", [:dress], "DRESS"),
      self.new("\u{1F458}", [:kimono], "KIMONO"),
      self.new("\u{1F97B}", [:sari], "SARI"),
      self.new("\u{1FA71}", [:"one-piece-swimsuit"], "ONE PIECE SWIMSUIT"),
      self.new("\u{1FA72}", [:briefs], "BRIEFS"),
      self.new("\u{1FA73}", [:shorts], "SHORTS"),
      self.new("\u{1F459}", [:bikini], "BIKINI"),
      self.new("\u{1F45B}", [:purse], "PURSE"),
      self.new("\u{1F45C}", [:handbag], "HANDBAG"),
      self.new("\u{1F45D}", [:clutch_bag], "CLUTCH BAG"),
      self.new("\u{1F6CD}", [:shopping_bags], "SHOPPING BAGS"),
      self.new("\u{1FA74}", [:thong_sandal], "THONG SANDAL"),
      self.new("\u{1F45F}", [:running_shoe], "RUNNING SHOE"),
      self.new("\u{1F97E}", [:hiking_boot], "HIKING BOOT"),
      self.new("\u{1F97F}", [:flat_shoe], "FLAT SHOE"),
      self.new("\u{1F460}", [:"high-heeled-shoe"], "HIGH HEELED SHOE"),
      self.new("\u{1FA70}", [:ballet_shoes], "BALLET SHOES"),
      self.new("\u{1F451}", [:crown], "CROWN"),
      self.new("\u{1F3A9}", [:top_hat], "TOP HAT"),
      self.new("\u{1FA96}", [:military_helmet], "MILITARY HELMET"),
      self.new("\u{1F4FF}", [:prayer_beads], "PRAYER BEADS"),
      self.new("\u{1F484}", [:lipstick], "LIPSTICK"),
      self.new("\u{1F48D}", [:ring], "RING"),
      self.new("\u{1F48E}", [:gem_stone], "GEM STONE"),
      self.new("\u{1F507}", [:muted_speaker], "MUTED SPEAKER"),
      self.new("\u{1F508}", [:speaker_low_volume], "SPEAKER LOW VOLUME"),
      self.new("\u{1F509}", [:speaker_medium_volume], "SPEAKER MEDIUM VOLUME"),
      self.new("\u{1F50A}", [:speaker_high_volume], "SPEAKER HIGH VOLUME"),
      self.new("\u{1F4E2}", [:loudspeaker], "LOUDSPEAKER"),
      self.new("\u{1F4E3}", [:megaphone], "MEGAPHONE"),
      self.new("\u{1F4EF}", [:postal_horn], "POSTAL HORN"),
      self.new("\u{1F514}", [:bell], "BELL"),
      self.new("\u{1F515}", [:bell_with_slash], "BELL WITH SLASH"),
      self.new("\u{1F3BC}", [:musical_score], "MUSICAL SCORE"),
      self.new("\u{1F399}", [:studio_microphone], "STUDIO MICROPHONE"),
      self.new("\u{1F39A}", [:level_slider], "LEVEL SLIDER"),
      self.new("\u{1F39B}", [:control_knobs], "CONTROL KNOBS"),
      self.new("\u{1F3A4}", [:microphone], "MICROPHONE"),
      self.new("\u{1F3A7}", [:headphone], "HEADPHONE"),
      self.new("\u{1F4FB}", [:radio], "RADIO"),
      self.new("\u{1F3B7}", [:saxophone], "SAXOPHONE"),
      self.new("\u{1FA97}", [:accordion], "ACCORDION"),
      self.new("\u{1F3B8}", [:guitar], "GUITAR"),
      self.new("\u{1F3B9}", [:musical_keyboard], "MUSICAL KEYBOARD"),
      self.new("\u{1F3BA}", [:trumpet], "TRUMPET"),
      self.new("\u{1F3BB}", [:violin], "VIOLIN"),
      self.new("\u{1FA95}", [:banjo], "BANJO"),
      self.new("\u{1FA98}", [:long_drum], "LONG DRUM"),
      self.new("\u{1F4F1}", [:mobile_phone], "MOBILE PHONE"),
      self.new("\u{1F4F2}", [:mobile_phone_with_arrow], "MOBILE PHONE WITH ARROW"),
      self.new("\u{260E}",  [:telephone], "TELEPHONE"),
      self.new("\u{1F4DE}", [:telephone_receiver], "TELEPHONE RECEIVER"),
      self.new("\u{1F4DF}", [:pager], "PAGER"),
      self.new("\u{1F4E0}", [:fax_machine], "FAX MACHINE"),
      self.new("\u{1F50B}", [:battery], "BATTERY"),
      self.new("\u{1FAAB}", [:low_battery], "LOW BATTERY"),
      self.new("\u{1F50C}", [:electric_plug], "ELECTRIC PLUG"),
      self.new("\u{1F4BB}", [:laptop], "LAPTOP"),
      self.new("\u{1F5A5}", [:desktop_computer], "DESKTOP COMPUTER"),
      self.new("\u{1F5A8}", [:printer], "PRINTER"),
      self.new("\u{1F5B1}", [:computer_mouse], "COMPUTER MOUSE"),
      self.new("\u{1F5B2}", [:trackball], "TRACKBALL"),
      self.new("\u{1F4BD}", [:computer_disk], "COMPUTER DISK"),
      self.new("\u{1F4BE}", [:floppy_disk], "FLOPPY DISK"),
      self.new("\u{1F4BF}", [:optical_disk], "OPTICAL DISK"),
      self.new("\u{1F4C0}", [:dvd], "DVD"),
      self.new("\u{1F9EE}", [:abacus], "ABACUS"),
      self.new("\u{1F3A5}", [:movie_camera], "MOVIE CAMERA"),
      self.new("\u{1F39E}", [:film_frames], "FILM FRAMES"),
      self.new("\u{1F4FD}", [:film_projector], "FILM PROJECTOR"),
      self.new("\u{1F3AC}", [:clapper_board], "CLAPPER BOARD"),
      self.new("\u{1F4FA}", [:television], "TELEVISION"),
      self.new("\u{1F4F7}", [:camera], "CAMERA"),
      self.new("\u{1F4F8}", [:camera_with_flash], "CAMERA WITH FLASH"),
      self.new("\u{1F4F9}", [:video_camera], "VIDEO CAMERA"),
      self.new("\u{1F4FC}", [:videocassette], "VIDEOCASSETTE"),
      self.new("\u{1F50D}", [:magnifying_glass_tilted_left], "MAGNIFYING GLASS TILTED LEFT"),
      self.new("\u{1F50E}", [:magnifying_glass_tilted_right], "MAGNIFYING GLASS TILTED RIGHT"),
      self.new("\u{1F56F}", [:candle], "CANDLE"),
      self.new("\u{1F4A1}", [:light_bulb], "LIGHT BULB"),
      self.new("\u{1F526}", [:flashlight], "FLASHLIGHT"),
      self.new("\u{1FA94}", [:diya_lamp], "DIYA LAMP"),
      self.new("\u{1F4D4}", [:notebook_with_decorative_cover], "NOTEBOOK WITH DECORATIVE COVER"),
      self.new("\u{1F4D5}", [:closed_book], "CLOSED BOOK"),
      self.new("\u{1F4D7}", [:green_book], "GREEN BOOK"),
      self.new("\u{1F4D8}", [:blue_book], "BLUE BOOK"),
      self.new("\u{1F4D9}", [:orange_book], "ORANGE BOOK"),
      self.new("\u{1F4DA}", [:books], "BOOKS"),
      self.new("\u{1F4D3}", [:notebook], "NOTEBOOK"),
      self.new("\u{1F4D2}", [:ledger], "LEDGER"),
      self.new("\u{1F4C3}", [:page_with_curl], "PAGE WITH CURL"),
      self.new("\u{1F4DC}", [:scroll], "SCROLL"),
      self.new("\u{1F4C4}", [:page_facing_up], "PAGE FACING UP"),
      self.new("\u{1F4F0}", [:newspaper], "NEWSPAPER"),
      self.new("\u{1F5DE}", [:"rolled-up-newspaper"], "ROLLED UP NEWSPAPER"),
      self.new("\u{1F4D1}", [:bookmark_tabs], "BOOKMARK TABS"),
      self.new("\u{1F516}", [:bookmark], "BOOKMARK"),
      self.new("\u{1F3F7}", [:label], "LABEL"),
      self.new("\u{1F4B0}", [:money_bag], "MONEY BAG"),
      self.new("\u{1FA99}", [:coin], "COIN"),
      self.new("\u{1F4B4}", [:yen_banknote], "YEN BANKNOTE"),
      self.new("\u{1F4B5}", [:dollar_banknote], "DOLLAR BANKNOTE"),
      self.new("\u{1F4B6}", [:euro_banknote], "EURO BANKNOTE"),
      self.new("\u{1F4B7}", [:pound_banknote], "POUND BANKNOTE"),
      self.new("\u{1F4B8}", [:money_with_wings], "MONEY WITH WINGS"),
      self.new("\u{1F4B3}", [:credit_card], "CREDIT CARD"),
      self.new("\u{1F9FE}", [:receipt], "RECEIPT"),
      self.new("\u{1F4B9}", [:chart_increasing_with_yen], "CHART INCREASING WITH YEN"),
      self.new("\u{1F4E8}", [:incoming_envelope], "INCOMING ENVELOPE"),
      self.new("\u{1F4E9}", [:envelope_with_arrow], "ENVELOPE WITH ARROW"),
      self.new("\u{1F4E4}", [:outbox_tray], "OUTBOX TRAY"),
      self.new("\u{1F4E5}", [:inbox_tray], "INBOX TRAY"),
      self.new("\u{1F4E6}", [:package], "PACKAGE"),
      self.new("\u{1F4EB}", [:closed_mailbox_with_raised_flag], "CLOSED MAILBOX WITH RAISED FLAG"),
      self.new("\u{1F4EA}", [:closed_mailbox_with_lowered_flag], "CLOSED MAILBOX WITH LOWERED FLAG"),
      self.new("\u{1F4EC}", [:open_mailbox_with_raised_flag], "OPEN MAILBOX WITH RAISED FLAG"),
      self.new("\u{1F4ED}", [:open_mailbox_with_lowered_flag], "OPEN MAILBOX WITH LOWERED FLAG"),
      self.new("\u{1F4EE}", [:postbox], "POSTBOX"),
      self.new("\u{1F5F3}", [:ballot_box_with_ballot], "BALLOT BOX WITH BALLOT"),
      self.new("\u{270F}", [:pencil], "PENCIL"),
      self.new("\u{1F58B}", [:fountain_pen], "FOUNTAIN PEN"),
      self.new("\u{1F58A}", [:pen], "PEN"),
      self.new("\u{1F58C}", [:paintbrush], "PAINTBRUSH"),
      self.new("\u{1F58D}", [:crayon], "CRAYON"),
      self.new("\u{1F4DD}", [:memo], "MEMO"),
      self.new("\u{1F4BC}", [:briefcase], "BRIEFCASE"),
      self.new("\u{1F4C1}", [:file_folder], "FILE FOLDER"),
      self.new("\u{1F4C2}", [:open_file_folder], "OPEN FILE FOLDER"),
      self.new("\u{1F5C2}", [:card_index_dividers], "CARD INDEX DIVIDERS"),
      self.new("\u{1F4C5}", [:calendar], "CALENDAR"),
      self.new("\u{1F4C6}", [:"tear-off-calendar"], "TEAR OFF CALENDAR"),
      self.new("\u{1F5D2}", [:spiral_notepad], "SPIRAL NOTEPAD"),
      self.new("\u{1F5D3}", [:spiral_calendar], "SPIRAL CALENDAR"),
      self.new("\u{1F4C7}", [:card_index], "CARD INDEX"),
      self.new("\u{1F4C8}", [:chart_increasing], "CHART INCREASING"),
      self.new("\u{1F4C9}", [:chart_decreasing], "CHART DECREASING"),
      self.new("\u{1F4CA}", [:bar_chart], "BAR CHART"),
      self.new("\u{1F4CB}", [:clipboard], "CLIPBOARD"),
      self.new("\u{1F4CC}", [:pushpin], "PUSHPIN"),
      self.new("\u{1F4CD}", [:round_pushpin], "ROUND PUSHPIN"),
      self.new("\u{1F4CE}", [:paperclip], "PAPERCLIP"),
      self.new("\u{1F587}", [:linked_paperclips], "LINKED PAPERCLIPS"),
      self.new("\u{1F4CF}", [:straight_ruler], "STRAIGHT RULER"),
      self.new("\u{1F4D0}", [:triangular_ruler], "TRIANGULAR RULER"),
      self.new("\u{1F5C3}", [:card_file_box], "CARD FILE BOX"),
      self.new("\u{1F5C4}", [:file_cabinet], "FILE CABINET"),
      self.new("\u{1F5D1}", [:wastebasket], "WASTEBASKET"),
      self.new("\u{1F512}", [:locked], "LOCKED"),
      self.new("\u{1F513}", [:unlocked], "UNLOCKED"),
      self.new("\u{1F50F}", [:locked_with_pen], "LOCKED WITH PEN"),
      self.new("\u{1F510}", [:locked_with_key], "LOCKED WITH KEY"),
      self.new("\u{1F511}", [:key], "KEY"),
      self.new("\u{1F5DD}", [:old_key], "OLD KEY"),
      self.new("\u{1F528}", [:hammer], "HAMMER"),
      self.new("\u{1FA93}", [:axe], "AXE"),
      self.new("\u{26CF}", [:pick], "PICK"),
      self.new("\u{1F6E0}", [:hammer_and_wrench], "HAMMER AND WRENCH"),
      self.new("\u{1F5E1}", [:dagger], "DAGGER"),
      self.new("\u{1F4A3}", [:bomb], "BOMB"),
      self.new("\u{1FA83}", [:boomerang], "BOOMERANG"),
      self.new("\u{1F3F9}", [:bow_and_arrow], "BOW AND ARROW"),
      self.new("\u{1F6E1}", [:shield], "SHIELD"),
      self.new("\u{1FA9A}", [:carpentry_saw], "CARPENTRY SAW"),
      self.new("\u{1F527}", [:wrench], "WRENCH"),
      self.new("\u{1FA9B}", [:screwdriver], "SCREWDRIVER"),
      self.new("\u{1F529}", [:nut_and_bolt], "NUT AND BOLT"),
      self.new("\u{1F5DC}", [:clamp], "CLAMP"),
      self.new("\u{1F9AF}", [:white_cane], "WHITE CANE"),
      self.new("\u{1F517}", [:link], "LINK"),
      self.new("\u{26D3}", [:chains], "CHAINS"),
      self.new("\u{1FA9D}", [:hook], "HOOK"),
      self.new("\u{1F9F0}", [:toolbox], "TOOLBOX"),
      self.new("\u{1F9F2}", [:magnet], "MAGNET"),
      self.new("\u{1FA9C}", [:ladder], "LADDER"),
      self.new("\u{1F9EA}", [:test_tube], "TEST TUBE"),
      self.new("\u{1F9EB}", [:petri_dish], "PETRI DISH"),
      self.new("\u{1F9EC}", [:dna], "DNA"),
      self.new("\u{1F52C}", [:microscope], "MICROSCOPE"),
      self.new("\u{1F52D}", [:telescope], "TELESCOPE"),
      self.new("\u{1F489}", [:syringe], "SYRINGE"),
      self.new("\u{1FA78}", [:drop_of_blood], "DROP OF BLOOD"),
      self.new("\u{1F48A}", [:pill], "PILL"),
      self.new("\u{1FA79}", [:adhesive_bandage], "ADHESIVE BANDAGE"),
      self.new("\u{1FA7C}", [:crutch], "CRUTCH"),
      self.new("\u{1FA7A}", [:stethoscope], "STETHOSCOPE"),
      self.new("\u{1FA7B}", [:"x-ray"], "X RAY"),
      self.new("\u{1F6AA}", [:door], "DOOR"),
      self.new("\u{1F6D7}", [:elevator], "ELEVATOR"),
      self.new("\u{1FA9E}", [:mirror], "MIRROR"),
      self.new("\u{1FA9F}", [:window], "WINDOW"),
      self.new("\u{1F6CF}", [:bed], "BED"),
      self.new("\u{1F6CB}", [:couch_and_lamp], "COUCH AND LAMP"),
      self.new("\u{1FA91}", [:chair], "CHAIR"),
      self.new("\u{1F6BD}", [:toilet], "TOILET"),
      self.new("\u{1FAA0}", [:plunger], "PLUNGER"),
      self.new("\u{1F6BF}", [:shower], "SHOWER"),
      self.new("\u{1F6C1}", [:bathtub], "BATHTUB"),
      self.new("\u{1FAA4}", [:mouse_trap], "MOUSE TRAP"),
      self.new("\u{1FA92}", [:razor], "RAZOR"),
      self.new("\u{1F9F4}", [:lotion_bottle], "LOTION BOTTLE"),
      self.new("\u{1F9F7}", [:safety_pin], "SAFETY PIN"),
      self.new("\u{1F9F9}", [:broom], "BROOM"),
      self.new("\u{1F9FA}", [:basket], "BASKET"),
      self.new("\u{1F9FB}", [:roll_of_paper], "ROLL OF PAPER"),
      self.new("\u{1FAA3}", [:bucket], "BUCKET"),
      self.new("\u{1F9FC}", [:soap], "SOAP"),
      self.new("\u{1FAE7}", [:bubbles], "BUBBLES"),
      self.new("\u{1FAA5}", [:toothbrush], "TOOTHBRUSH"),
      self.new("\u{1F9FD}", [:sponge], "SPONGE"),
      self.new("\u{1F9EF}", [:fire_extinguisher], "FIRE EXTINGUISHER"),
      self.new("\u{1F6AC}", [:cigarette], "CIGARETTE"),
      self.new("\u{26B0}", [:coffin], "COFFIN"),
      self.new("\u{1FAA6}", [:headstone], "HEADSTONE"),
      self.new("\u{26B1}", [:funeral_urn], "FUNERAL URN"),
      self.new("\u{1F9FF}", [:nazar_amulet], "NAZAR AMULET"),
      self.new("\u{1FAAC}", [:hamsa], "HAMSA"),
      self.new("\u{1F5FF}", [:moai], "MOAI"),
      self.new("\u{1FAA7}", [:placard], "PLACARD"),
      self.new("\u{1FAAA}", [:identification_card], "IDENTIFICATION CARD"),
      self.new("\u{1F3E7}", [:ATM_sign], "ATM SIGN"),
      self.new("\u{1F6AE}", [:litter_in_bin_sign], "LITTER IN BIN SIGN"),
      self.new("\u{1F6B0}", [:potable_water], "POTABLE WATER"),
      self.new("\u{267F}", [:wheelchair_symbol], "WHEELCHAIR SYMBOL"),
      self.new("\u{1F6BB}", [:restroom], "RESTROOM"),
      self.new("\u{1F6BC}", [:baby_symbol], "BABY SYMBOL"),
      self.new("\u{1F6BE}", [:water_closet], "WATER CLOSET"),
      self.new("\u{1F6C2}", [:passport_control], "PASSPORT CONTROL"),
      self.new("\u{1F6C3}", [:customs], "CUSTOMS"),
      self.new("\u{1F6C4}", [:baggage_claim], "BAGGAGE CLAIM"),
      self.new("\u{1F6C5}", [:left_luggage], "LEFT LUGGAGE"),
      self.new("\u{26A0}", [:warning], "WARNING"),
      self.new("\u{1F6B8}", [:children_crossing], "CHILDREN CROSSING"),
      self.new("\u{26D4}", [:no_entry], "NO ENTRY"),
      self.new("\u{1F6AB}", [:prohibited], "PROHIBITED"),
      self.new("\u{1F6B3}", [:no_bicycles], "NO BICYCLES"),
      self.new("\u{1F6AD}", [:no_smoking], "NO SMOKING"),
      self.new("\u{1F6AF}", [:no_littering], "NO LITTERING"),
      self.new("\u{1F6B1}", [:"non-potable-water"], "NON POTABLE WATER"),
      self.new("\u{1F6B7}", [:no_pedestrians], "NO PEDESTRIANS"),
      self.new("\u{1F4F5}", [:no_mobile_phones], "NO MOBILE PHONES"),
      self.new("\u{1F51E}", [:no_one_under_eighteen], "NO ONE UNDER EIGHTEEN"),
      self.new("\u{2B06}", [:up_arrow], "UP ARROW"),
      self.new("\u{27A1}", [:right_arrow], "RIGHT ARROW"),
      self.new("\u{2B07}", [:down_arrow], "DOWN ARROW"),
      self.new("\u{2B05}", [:left_arrow], "LEFT ARROW"),
      self.new("\u{21A9}", [:right_arrow_curving_left], "RIGHT ARROW CURVING LEFT"),
      self.new("\u{21AA}", [:left_arrow_curving_right], "LEFT ARROW CURVING RIGHT"),
      self.new("\u{1F503}", [:clockwise_vertical_arrows], "CLOCKWISE VERTICAL ARROWS"),
      self.new("\u{1F504}", [:counterclockwise_arrows_button], "COUNTERCLOCKWISE ARROWS BUTTON"),
      self.new("\u{1F519}", [:BACK_arrow], "BACK ARROW"),
      self.new("\u{1F51A}", [:END_arrow], "END ARROW"),
      self.new("\u{1F51B}", [:ON_arrow], "ON ARROW"),
      self.new("\u{1F51C}", [:SOON_arrow], "SOON ARROW"),
      self.new("\u{1F51D}", [:TOP_arrow], "TOP ARROW"),
      self.new("\u{1F6D0}", [:place_of_worship], "PLACE OF WORSHIP"),
      self.new("\u{269B}", [:atom_symbol], "ATOM SYMBOL"),
      self.new("\u{1F549}", [:om], "OM"),
      self.new("\u{262F}", [:yin_yang], "YIN YANG"),
      self.new("\u{271D}", [:latin_cross], "LATIN CROSS"),
      self.new("\u{262A}", [:star_and_crescent], "STAR AND CRESCENT"),
      self.new("\u{262E}", [:peace_symbol], "PEACE SYMBOL"),
      self.new("\u{1F54E}", [:menorah], "MENORAH"),
      self.new("\u{1F52F}", [:"dotted-six-pointed_star"], "DOTTED SIX POINTED STAR"),
      self.new("\u{264A}", [:Gemini], "GEMINI"),
      self.new("\u{264B}", [:Cancer], "CANCER"),
      self.new("\u{264C}", [:Leo], "LEO"),
      self.new("\u{264D}", [:Virgo], "VIRGO"),
      self.new("\u{264E}", [:Libra], "LIBRA"),
      self.new("\u{264F}", [:Scorpio], "SCORPIO"),
      self.new("\u{26CE}", [:Ophiuchus], "OPHIUCHUS"),
      self.new("\u{1F500}", [:shuffle_tracks_button], "SHUFFLE TRACKS BUTTON"),
      self.new("\u{1F501}", [:repeat_button], "REPEAT BUTTON"),
      self.new("\u{1F502}", [:repeat_single_button], "REPEAT SINGLE BUTTON"),
      self.new("\u{25B6}", [:play_button], "PLAY BUTTON"),
      self.new("\u{23E9}", [:"fast-forward-button"], "FAST FORWARD BUTTON"),
      self.new("\u{23ED}", [:next_track_button], "NEXT TRACK BUTTON"),
      self.new("\u{23EF}", [:play_or_pause_button], "PLAY OR PAUSE BUTTON"),
      self.new("\u{25C0}", [:reverse_button], "REVERSE BUTTON"),
      self.new("\u{23EA}", [:fast_reverse_button], "FAST REVERSE BUTTON"),
      self.new("\u{23EE}", [:last_track_button], "LAST TRACK BUTTON"),
      self.new("\u{1F53C}", [:upwards_button], "UPWARDS BUTTON"),
      self.new("\u{23EB}", [:fast_up_button], "FAST UP BUTTON"),
      self.new("\u{1F53D}", [:downwards_button], "DOWNWARDS BUTTON"),
      self.new("\u{23EC}", [:fast_down_button], "FAST DOWN BUTTON"),
      self.new("\u{23F8}", [:pause_button], "PAUSE BUTTON"),
      self.new("\u{23F9}", [:stop_button], "STOP BUTTON"),
      self.new("\u{23FA}", [:record_button], "RECORD BUTTON"),
      self.new("\u{23CF}", [:eject_button], "EJECT BUTTON"),
      self.new("\u{1F3A6}", [:cinema], "CINEMA"),
      self.new("\u{1F505}", [:dim_button], "DIM BUTTON"),
      self.new("\u{1F506}", [:bright_button], "BRIGHT BUTTON"),
      self.new("\u{1F4F6}", [:antenna_bars], "ANTENNA BARS"),
      self.new("\u{1F4F3}", [:vibration_mode], "VIBRATION MODE"),
      self.new("\u{1F4F4}", [:mobile_phone_off], "MOBILE PHONE OFF"),
      self.new("\u{2640}", [:female_sign], "FEMALE SIGN"),
      self.new("\u{2642}", [:male_sign], "MALE SIGN"),
      self.new("\u{26A7}", [:transgender_symbol], "TRANSGENDER SYMBOL"),
      self.new("\u{1F7F0}", [:heavy_equals_sign], "HEAVY EQUALS SIGN"),
      self.new("\u{267E}", [:infinity], "INFINITY"),
      self.new("\u{203C}", [:double_exclamation_mark], "DOUBLE EXCLAMATION MARK"),
      self.new("\u{1F4B1}", [:currency_exchange], "CURRENCY EXCHANGE"),
      self.new("\u{1F4B2}", [:heavy_dollar_sign], "HEAVY DOLLAR SIGN"),
      self.new("\u{2695}", [:medical_symbol], "MEDICAL SYMBOL"),
      self.new("\u{267B}", [:recycling_symbol], "RECYCLING SYMBOL"),
      self.new("\u{269C}", [:"fleur-de-lis"], "FLEUR DE LIS"),
      self.new("\u{1F531}", [:trident_emblem], "TRIDENT EMBLEM"),
      self.new("\u{1F4DB}", [:name_badge], "NAME BADGE"),
      self.new("\u{1F530}", [:Japanese_symbol_for_beginner], "JAPANESE SYMBOL FOR BEGINNER"),
      self.new("\u{2B55}", [:hollow_red_circle], "HOLLOW RED CIRCLE"),
      self.new("\u{274C}", [:cross_mark], "CROSS MARK"),
      self.new("\u{274E}", [:cross_mark_button], "CROSS MARK BUTTON"),
      self.new("\u{27B0}", [:curly_loop], "CURLY LOOP"),
      self.new("\u{27BF}", [:double_curly_loop], "DOUBLE CURLY LOOP"),
      self.new("\u{303D}", [:part_alternation_mark], "PART ALTERNATION MARK"),
      self.new("\u{00A9}", [:copyright], "COPYRIGHT"),
      self.new("\u{00AE}", [:registered], "REGISTERED"),
      self.new("\u{1F520}", [:input_latin_uppercase], "INPUT LATIN UPPERCASE"),
      self.new("\u{1F521}", [:input_latin_lowercase], "INPUT LATIN LOWERCASE"),
      self.new("\u{1F522}", [:input_numbers], "INPUT NUMBERS"),
      self.new("\u{1F523}", [:input_symbols], "INPUT SYMBOLS"),
      self.new("\u{1F524}", [:input_latin_letters], "INPUT LATIN LETTERS"),
      self.new("\u{1F191}", [:CL_button], "CL BUTTON"),
      self.new("\u{1F192}", [:COOL_button], "COOL BUTTON"),
      self.new("\u{1F193}", [:FREE_button], "FREE BUTTON"),
      self.new("\u{1F194}", [:ID_button], "ID BUTTON"),
      self.new("\u{24C2}", [:circled_M], "CIRCLED M"),
      self.new("\u{1F195}", [:NEW_button], "NEW BUTTON"),
      self.new("\u{1F196}", [:NG_button], "NG BUTTON"),
      self.new("\u{1F197}", [:OK_button], "OK BUTTON"),
      self.new("\u{1F17F}", [:P_button], "P BUTTON"),
      self.new("\u{1F198}", [:SOS_button], "SOS BUTTON"),
      self.new("\u{1F19A}", [:VS_button], "VS BUTTON"),
      self.new("\u{1F534}", [:red_circle], "RED CIRCLE"),
      self.new("\u{1F7E0}", [:orange_circle], "ORANGE CIRCLE"),
      self.new("\u{1F7E1}", [:yellow_circle], "YELLOW CIRCLE"),
      self.new("\u{1F7E2}", [:green_circle], "GREEN CIRCLE"),
      self.new("\u{1F535}", [:blue_circle], "BLUE CIRCLE"),
      self.new("\u{1F7E3}", [:purple_circle], "PURPLE CIRCLE"),
      self.new("\u{1F7E4}", [:brown_circle], "BROWN CIRCLE"),
      self.new("\u{26AB}", [:black_circle], "BLACK CIRCLE"),
      self.new("\u{26AA}", [:white_circle], "WHITE CIRCLE"),
      self.new("\u{1F7E5}", [:red_square], "RED SQUARE"),
      self.new("\u{1F7E7}", [:orange_square], "ORANGE SQUARE"),
      self.new("\u{1F7E8}", [:yellow_square], "YELLOW SQUARE"),
      self.new("\u{1F7E9}", [:green_square], "GREEN SQUARE"),
      self.new("\u{1F7E6}", [:blue_square], "BLUE SQUARE"),
      self.new("\u{1F7EA}", [:purple_square], "PURPLE SQUARE"),
      self.new("\u{1F7EB}", [:brown_square], "BROWN SQUARE"),
      self.new("\u{2B1B}", [:black_large_square], "BLACK LARGE SQUARE"),
      self.new("\u{2B1C}", [:white_large_square], "WHITE LARGE SQUARE"),
      self.new("\u{25FC}", [:black_medium_square], "BLACK MEDIUM SQUARE"),
      self.new("\u{25FB}", [:white_medium_square], "WHITE MEDIUM SQUARE"),
      self.new("\u{25FE}", [:"black-medium-small-square"], "BLACK MEDIUM SMALL SQUARE"),
      self.new("\u{25FD}", [:"white-medium-small-square"], "WHITE MEDIUM SMALL SQUARE"),
      self.new("\u{25AA}", [:black_small_square], "BLACK SMALL SQUARE"),
      self.new("\u{25AB}", [:white_small_square], "WHITE SMALL SQUARE"),
      self.new("\u{1F536}", [:large_orange_diamond], "LARGE ORANGE DIAMOND"),
      self.new("\u{1F537}", [:large_blue_diamond], "LARGE BLUE DIAMOND"),
      self.new("\u{1F538}", [:small_orange_diamond], "SMALL ORANGE DIAMOND"),
      self.new("\u{1F539}", [:small_blue_diamond], "SMALL BLUE DIAMOND"),
      self.new("\u{1F53A}", [:red_triangle_pointed_up], "RED TRIANGLE POINTED UP"),
      self.new("\u{1F53B}", [:red_triangle_pointed_down], "RED TRIANGLE POINTED DOWN"),
      self.new("\u{1F4A0}", [:diamond_with_a_dot], "DIAMOND WITH A DOT"),
      self.new("\u{1F518}", [:radio_button], "RADIO BUTTON"),
      self.new("\u{1F533}", [:white_square_button], "WHITE SQUARE BUTTON"),
      self.new("\u{1F532}", [:black_square_button], "BLACK SQUARE BUTTON"),
      self.new("\u{1F3C1}", [:chequered_flag], "CHEQUERED FLAG"),
      self.new("\u{1F6A9}", [:triangular_flag], "TRIANGULAR FLAG"),
      self.new("\u{1F38C}", [:crossed_flags], "CROSSED FLAGS"),
      self.new("\u{1F3F4}", [:black_flag], "BLACK FLAG"),
      self.new("\u{1F3F3}", [:white_flag], "WHITE FLAG"),
      self.new("\u{1F1E6 1F1E8}", [:flag_Ascension_Island], "FLAG ASCENSION ISLAND"),
      self.new("\u{1F1E6 1F1E9}", [:flag_Andorra], "FLAG ANDORRA"),
      self.new("\u{1F1E6 1F1EA}", [:flag_United_Arab_Emirates], "FLAG UNITED ARAB EMIRATES"),
      self.new("\u{1F1E6 1F1EB}", [:flag_Afghanistan], "FLAG AFGHANISTAN"),
      self.new("\u{1F1E6 1F1EC}", [:flag_Antigua_Barbuda], "FLAG ANTIGUA BARBUDA"),
      self.new("\u{1F1E6 1F1EE}", [:flag_Anguilla], "FLAG ANGUILLA"),
      self.new("\u{1F1E6 1F1F1}", [:flag_Albania], "FLAG ALBANIA"),
      self.new("\u{1F1E6 1F1F2}", [:flag_Armenia], "FLAG ARMENIA"),
      self.new("\u{1F1E6 1F1F4}", [:flag_Angola], "FLAG ANGOLA"),
      self.new("\u{1F1E6 1F1F6}", [:flag_Antarctica], "FLAG ANTARCTICA"),
      self.new("\u{1F1E6 1F1F7}", [:flag_Argentina], "FLAG ARGENTINA"),
      self.new("\u{1F1E6 1F1F8}", [:flag_American_Samoa], "FLAG AMERICAN SAMOA"),
      self.new("\u{1F1E6 1F1F9}", [:flag_Austria], "FLAG AUSTRIA"),
      self.new("\u{1F1E6 1F1FA}", [:flag_Australia], "FLAG AUSTRALIA"),
      self.new("\u{1F1E6 1F1FC}", [:flag_Aruba], "FLAG ARUBA"),
      self.new("\u{1F1E6 1F1FD}", [:flag_Åland_Islands], "FLAG ÅLAND ISLANDS"),
      self.new("\u{1F1E6 1F1FF}", [:flag_Azerbaijan], "FLAG AZERBAIJAN"),
      self.new("\u{1F1E7 1F1E6}", [:flag_Bosnia_Herzegovina], "FLAG BOSNIA HERZEGOVINA"),
      self.new("\u{1F1E7 1F1E7}", [:flag_Barbados], "FLAG BARBADOS"),
      self.new("\u{1F1E7 1F1E9}", [:flag_Bangladesh], "FLAG BANGLADESH"),
      self.new("\u{1F1E7 1F1EA}", [:flag_Belgium], "FLAG BELGIUM"),
      self.new("\u{1F1E7 1F1EB}", [:flag_Burkina_Faso], "FLAG BURKINA FASO"),
      self.new("\u{1F1E7 1F1EC}", [:flag_Bulgaria], "FLAG BULGARIA"),
      self.new("\u{1F1E7 1F1ED}", [:flag_Bahrain], "FLAG BAHRAIN"),
      self.new("\u{1F1E7 1F1EE}", [:flag_Burundi], "FLAG BURUNDI"),
      self.new("\u{1F1E7 1F1EF}", [:flag_Benin], "FLAG BENIN"),
      self.new("\u{1F1E7 1F1F1}", [:flag_St_Barthélemy], "FLAG ST BARTHÉLEMY"),
      self.new("\u{1F1E7 1F1F2}", [:flag_Bermuda], "FLAG BERMUDA"),
      self.new("\u{1F1E7 1F1F4}", [:flag_Bolivia], "FLAG BOLIVIA"),
      self.new("\u{1F1E7 1F1F6}", [:flag_Caribbean_Netherlands], "FLAG CARIBBEAN NETHERLANDS"),
      self.new("\u{1F1E7 1F1F7}", [:flag_Brazil], "FLAG BRAZIL"),
      self.new("\u{1F1E7 1F1F8}", [:flag_Bahamas], "FLAG BAHAMAS"),
      self.new("\u{1F1E7 1F1F9}", [:flag_Bhutan], "FLAG BHUTAN"),
      self.new("\u{1F1E7 1F1FB}", [:flag_Bouvet_Island], "FLAG BOUVET ISLAND"),
      self.new("\u{1F1E7 1F1FC}", [:flag_Botswana], "FLAG BOTSWANA"),
      self.new("\u{1F1E7 1F1FE}", [:flag_Belarus], "FLAG BELARUS"),
      self.new("\u{1F1E7 1F1FF}", [:flag_Belize], "FLAG BELIZE"),
      self.new("\u{1F1E8 1F1E6}", [:flag_Canada], "FLAG CANADA"),
      self.new("\u{1F1E8 1F1E9}", [:flag_Congo_Kinshasa], "FLAG CONGO KINSHASA"),
      self.new("\u{1F1E8 1F1EB}", [:flag_Central_African_Republic], "FLAG CENTRAL AFRICAN REPUBLIC"),
      self.new("\u{1F1E8 1F1EC}", [:flag_Congo_Brazzaville], "FLAG CONGO BRAZZAVILLE"),
      self.new("\u{1F1E8 1F1ED}", [:flag_Switzerland], "FLAG SWITZERLAND"),
      self.new("\u{1F1E8 1F1F0}", [:flag_Cook_Islands], "FLAG COOK ISLANDS"),
      self.new("\u{1F1E8 1F1F1}", [:flag_Chile], "FLAG CHILE"),
      self.new("\u{1F1E8 1F1F2}", [:flag_Cameroon], "FLAG CAMEROON"),
      self.new("\u{1F1E8 1F1F4}", [:flag_Colombia], "FLAG COLOMBIA"),
      self.new("\u{1F1E8 1F1F5}", [:flag_Clipperton_Island], "FLAG CLIPPERTON ISLAND"),
      self.new("\u{1F1E8 1F1F7}", [:flag_Costa_Rica], "FLAG COSTA RICA"),
      self.new("\u{1F1E8 1F1FA}", [:flag_Cuba], "FLAG CUBA"),
      self.new("\u{1F1E8 1F1FB}", [:flag_Cape_Verde], "FLAG CAPE VERDE"),
      self.new("\u{1F1E8 1F1FC}", [:flag_Curaçao], "FLAG CURAÇAO"),
      self.new("\u{1F1E8 1F1FD}", [:flag_Christmas_Island], "FLAG CHRISTMAS ISLAND"),
      self.new("\u{1F1E8 1F1FE}", [:flag_Cyprus], "FLAG CYPRUS"),
      self.new("\u{1F1E8 1F1FF}", [:flag_Czechia], "FLAG CZECHIA"),
      self.new("\u{1F1E9 1F1EA}", [:flag_Germany], "FLAG GERMANY"),
      self.new("\u{1F1E9 1F1EC}", [:flag_Diego_Garcia], "FLAG DIEGO GARCIA"),
      self.new("\u{1F1E9 1F1EF}", [:flag_Djibouti], "FLAG DJIBOUTI"),
      self.new("\u{1F1E9 1F1F0}", [:flag_Denmark], "FLAG DENMARK"),
      self.new("\u{1F1E9 1F1F2}", [:flag_Dominica], "FLAG DOMINICA"),
      self.new("\u{1F1E9 1F1F4}", [:flag_Dominican_Republic], "FLAG DOMINICAN REPUBLIC"),
      self.new("\u{1F1E9 1F1FF}", [:flag_Algeria], "FLAG ALGERIA"),
      self.new("\u{1F1EA 1F1E6}", [:flag_Ceuta_Melilla], "FLAG CEUTA MELILLA"),
      self.new("\u{1F1EA 1F1E8}", [:flag_Ecuador], "FLAG ECUADOR"),
      self.new("\u{1F1EA 1F1EA}", [:flag_Estonia], "FLAG ESTONIA"),
      self.new("\u{1F1EA 1F1EC}", [:flag_Egypt], "FLAG EGYPT"),
      self.new("\u{1F1EA 1F1ED}", [:flag_Western_Sahara], "FLAG WESTERN SAHARA"),
      self.new("\u{1F1EA 1F1F7}", [:flag_Eritrea], "FLAG ERITREA"),
      self.new("\u{1F1EA 1F1F8}", [:flag_Spain], "FLAG SPAIN"),
      self.new("\u{1F1EA 1F1F9}", [:flag_Ethiopia], "FLAG ETHIOPIA"),
      self.new("\u{1F1EA 1F1FA}", [:flag_European_Union], "FLAG EUROPEAN UNION"),
      self.new("\u{1F1EB 1F1EE}", [:flag_Finland], "FLAG FINLAND"),
      self.new("\u{1F1EB 1F1EF}", [:flag_Fiji], "FLAG FIJI"),
      self.new("\u{1F1EB 1F1F0}", [:flag_Falkland_Islands], "FLAG FALKLAND ISLANDS"),
      self.new("\u{1F1EB 1F1F2}", [:flag_Micronesia], "FLAG MICRONESIA"),
      self.new("\u{1F1EB 1F1F4}", [:flag_Faroe_Islands], "FLAG FAROE ISLANDS"),
      self.new("\u{1F1EB 1F1F7}", [:flag_France], "FLAG FRANCE"),
      self.new("\u{1F1EC 1F1E6}", [:flag_Gabon], "FLAG GABON"),
      self.new("\u{1F1EC 1F1E7}", [:flag_United_Kingdom], "FLAG UNITED KINGDOM"),
      self.new("\u{1F1EC 1F1E9}", [:flag_Grenada], "FLAG GRENADA"),
      self.new("\u{1F1EC 1F1EA}", [:flag_Georgia], "FLAG GEORGIA"),
      self.new("\u{1F1EC 1F1EB}", [:flag_French_Guiana], "FLAG FRENCH GUIANA"),
      self.new("\u{1F1EC 1F1EC}", [:flag_Guernsey], "FLAG GUERNSEY"),
      self.new("\u{1F1EC 1F1ED}", [:flag_Ghana], "FLAG GHANA"),
      self.new("\u{1F1EC 1F1EE}", [:flag_Gibraltar], "FLAG GIBRALTAR"),
      self.new("\u{1F1EC 1F1F1}", [:flag_Greenland], "FLAG GREENLAND"),
      self.new("\u{1F1EC 1F1F2}", [:flag_Gambia], "FLAG GAMBIA"),
      self.new("\u{1F1EC 1F1F5}", [:flag_Guadeloupe], "FLAG GUADELOUPE"),
      self.new("\u{1F1EC 1F1F6}", [:flag_Equatorial_Guinea], "FLAG EQUATORIAL GUINEA"),
      self.new("\u{1F1EC 1F1F7}", [:flag_Greece], "FLAG GREECE"),
      self.new("\u{1F1EC 1F1F8}", [:flag_South_Georgia_South_Sandwich_Islands], "FLAG SOUTH GEORGIA SOUTH SANDWICH ISLANDS"),
      self.new("\u{1F1EC 1F1F9}", [:flag_Guatemala], "FLAG GUATEMALA"),
      self.new("\u{1F1EC 1F1FA}", [:flag_Guam], "FLAG GUAM"),
      self.new("\u{1F1EC 1F1FC}", [:"flag-Guinea-Bissau"], "FLAG GUINEA BISSAU"),
      self.new("\u{1F1EC 1F1FE}", [:flag_Guyana], "FLAG GUYANA"),
      self.new("\u{1F1ED 1F1F0}", [:flag_Hong_Kong_SAR_China], "FLAG HONG KONG SAR CHINA"),
      self.new("\u{1F1ED 1F1F2}", [:flag_Heard_McDonald_Islands], "FLAG HEARD MCDONALD ISLANDS"),
      self.new("\u{1F1ED 1F1F7}", [:flag_Croatia], "FLAG CROATIA"),
      self.new("\u{1F1ED 1F1F9}", [:flag_Haiti], "FLAG HAITI"),
      self.new("\u{1F1ED 1F1FA}", [:flag_Hungary], "FLAG HUNGARY"),
      self.new("\u{1F1EE 1F1E8}", [:flag_Canary_Islands], "FLAG CANARY ISLANDS"),
      self.new("\u{1F1EE 1F1E9}", [:flag_Indonesia], "FLAG INDONESIA"),
      self.new("\u{1F1EE 1F1EA}", [:flag_Ireland], "FLAG IRELAND"),
      self.new("\u{1F1EE 1F1F1}", [:flag_Israel], "FLAG ISRAEL"),
      self.new("\u{1F1EE 1F1F2}", [:flag_Isle_of_Man], "FLAG ISLE OF MAN"),
      self.new("\u{1F1EE 1F1F4}", [:flag_British_Indian_Ocean_Territory], "FLAG BRITISH INDIAN OCEAN TERRITORY"),
      self.new("\u{1F1EE 1F1F6}", [:flag_Iraq], "FLAG IRAQ"),
      self.new("\u{1F1EE 1F1F7}", [:flag_Iran], "FLAG IRAN"),
      self.new("\u{1F1EE 1F1F8}", [:flag_Iceland], "FLAG ICELAND"),
      self.new("\u{1F1EE 1F1F9}", [:flag_Italy], "FLAG ITALY"),
      self.new("\u{1F1EF 1F1EA}", [:flag_Jersey], "FLAG JERSEY"),
      self.new("\u{1F1EF 1F1F2}", [:flag_Jamaica], "FLAG JAMAICA"),
      self.new("\u{1F1EF 1F1F4}", [:flag_Jordan], "FLAG JORDAN"),
      self.new("\u{1F1EF 1F1F5}", [:flag_Japan], "FLAG JAPAN"),
      self.new("\u{1F1F0 1F1EA}", [:flag_Kenya], "FLAG KENYA"),
      self.new("\u{1F1F0 1F1EC}", [:flag_Kyrgyzstan], "FLAG KYRGYZSTAN"),
      self.new("\u{1F1F0 1F1ED}", [:flag_Cambodia], "FLAG CAMBODIA"),
      self.new("\u{1F1F0 1F1EE}", [:flag_Kiribati], "FLAG KIRIBATI"),
      self.new("\u{1F1F0 1F1F2}", [:flag_Comoros], "FLAG COMOROS"),
      self.new("\u{1F1F0 1F1F5}", [:flag_North_Korea], "FLAG NORTH KOREA"),
      self.new("\u{1F1F0 1F1F7}", [:flag_South_Korea], "FLAG SOUTH KOREA"),
      self.new("\u{1F1F0 1F1FC}", [:flag_Kuwait], "FLAG KUWAIT"),
      self.new("\u{1F1F0 1F1FE}", [:flag_Cayman_Islands], "FLAG CAYMAN ISLANDS"),
      self.new("\u{1F1F0 1F1FF}", [:flag_Kazakhstan], "FLAG KAZAKHSTAN"),
      self.new("\u{1F1F1 1F1E6}", [:flag_Laos], "FLAG LAOS"),
      self.new("\u{1F1F1 1F1E7}", [:flag_Lebanon], "FLAG LEBANON"),
      self.new("\u{1F1F1 1F1E8}", [:flag_St_Lucia], "FLAG ST LUCIA"),
      self.new("\u{1F1F1 1F1EE}", [:flag_Liechtenstein], "FLAG LIECHTENSTEIN"),
      self.new("\u{1F1F1 1F1F0}", [:flag_Sri_Lanka], "FLAG SRI LANKA"),
      self.new("\u{1F1F1 1F1F7}", [:flag_Liberia], "FLAG LIBERIA"),
      self.new("\u{1F1F1 1F1F8}", [:flag_Lesotho], "FLAG LESOTHO"),
      self.new("\u{1F1F1 1F1F9}", [:flag_Lithuania], "FLAG LITHUANIA"),
      self.new("\u{1F1F1 1F1FA}", [:flag_Luxembourg], "FLAG LUXEMBOURG"),
      self.new("\u{1F1F1 1F1FB}", [:flag_Latvia], "FLAG LATVIA"),
      self.new("\u{1F1F1 1F1FE}", [:flag_Libya], "FLAG LIBYA"),
      self.new("\u{1F1F2 1F1E6}", [:flag_Morocco], "FLAG MOROCCO"),
      self.new("\u{1F1F2 1F1E8}", [:flag_Monaco], "FLAG MONACO"),
      self.new("\u{1F1F2 1F1E9}", [:flag_Moldova], "FLAG MOLDOVA"),
      self.new("\u{1F1F2 1F1EA}", [:flag_Montenegro], "FLAG MONTENEGRO"),
      self.new("\u{1F1F2 1F1EB}", [:flag_St_Martin], "FLAG ST MARTIN"),
      self.new("\u{1F1F2 1F1EC}", [:flag_Madagascar], "FLAG MADAGASCAR"),
      self.new("\u{1F1F2 1F1ED}", [:flag_Marshall_Islands], "FLAG MARSHALL ISLANDS"),
      self.new("\u{1F1F2 1F1F0}", [:flag_North_Macedonia], "FLAG NORTH MACEDONIA"),
      self.new("\u{1F1F2 1F1F1}", [:flag_Mali], "FLAG MALI"),
      self.new("\u{1F1F2 1F1F4}", [:flag_Macao_SAR_China], "FLAG MACAO SAR CHINA"),
      self.new("\u{1F1F2 1F1F5}", [:flag_Northern_Mariana_Islands], "FLAG NORTHERN MARIANA ISLANDS"),
      self.new("\u{1F1F2 1F1F6}", [:flag_Martinique], "FLAG MARTINIQUE"),
      self.new("\u{1F1F2 1F1F7}", [:flag_Mauritania], "FLAG MAURITANIA"),
      self.new("\u{1F1F2 1F1F8}", [:flag_Montserrat], "FLAG MONTSERRAT"),
      self.new("\u{1F1F2 1F1F9}", [:flag_Malta], "FLAG MALTA"),
      self.new("\u{1F1F2 1F1FA}", [:flag_Mauritius], "FLAG MAURITIUS"),
      self.new("\u{1F1F2 1F1FB}", [:flag_Maldives], "FLAG MALDIVES"),
      self.new("\u{1F1F2 1F1FC}", [:flag_Malawi], "FLAG MALAWI"),
      self.new("\u{1F1F2 1F1FD}", [:flag_Mexico], "FLAG MEXICO"),
      self.new("\u{1F1F2 1F1FE}", [:flag_Malaysia], "FLAG MALAYSIA"),
      self.new("\u{1F1F2 1F1FF}", [:flag_Mozambique], "FLAG MOZAMBIQUE"),
      self.new("\u{1F1F3 1F1E6}", [:flag_Namibia], "FLAG NAMIBIA"),
      self.new("\u{1F1F3 1F1E8}", [:flag_New_Caledonia], "FLAG NEW CALEDONIA"),
      self.new("\u{1F1F3 1F1EA}", [:flag_Niger], "FLAG NIGER"),
      self.new("\u{1F1F3 1F1EB}", [:flag_Norfolk_Island], "FLAG NORFOLK ISLAND"),
      self.new("\u{1F1F3 1F1EC}", [:flag_Nigeria], "FLAG NIGERIA"),
      self.new("\u{1F1F3 1F1EE}", [:flag_Nicaragua], "FLAG NICARAGUA"),
      self.new("\u{1F1F3 1F1F1}", [:flag_Netherlands], "FLAG NETHERLANDS"),
      self.new("\u{1F1F3 1F1F4}", [:flag_Norway], "FLAG NORWAY"),
      self.new("\u{1F1F3 1F1F5}", [:flag_Nepal], "FLAG NEPAL"),
      self.new("\u{1F1F3 1F1F7}", [:flag_Nauru], "FLAG NAURU"),
      self.new("\u{1F1F3 1F1FA}", [:flag_Niue], "FLAG NIUE"),
      self.new("\u{1F1F3 1F1FF}", [:flag_New_Zealand], "FLAG NEW ZEALAND"),
      self.new("\u{1F1F4 1F1F2}", [:flag_Oman], "FLAG OMAN"),
      self.new("\u{1F1F5 1F1E6}", [:flag_Panama], "FLAG PANAMA"),
      self.new("\u{1F1F5 1F1EA}", [:flag_Peru], "FLAG PERU"),
      self.new("\u{1F1F5 1F1EB}", [:flag_French_Polynesia], "FLAG FRENCH POLYNESIA"),
      self.new("\u{1F1F5 1F1EC}", [:flag_Papua_New_Guinea], "FLAG PAPUA NEW GUINEA"),
      self.new("\u{1F1F5 1F1ED}", [:flag_Philippines], "FLAG PHILIPPINES"),
      self.new("\u{1F1F5 1F1F0}", [:flag_Pakistan], "FLAG PAKISTAN"),
      self.new("\u{1F1F5 1F1F1}", [:flag_Poland], "FLAG POLAND"),
      self.new("\u{1F1F5 1F1F2}", [:flag_St_Pierre_Miquelon], "FLAG ST PIERRE MIQUELON"),
      self.new("\u{1F1F5 1F1F7}", [:flag_Puerto_Rico], "FLAG PUERTO RICO"),
      self.new("\u{1F1F5 1F1F8}", [:flag_Palestinian_Territories], "FLAG PALESTINIAN TERRITORIES"),
      self.new("\u{1F1F5 1F1F9}", [:flag_Portugal], "FLAG PORTUGAL"),
      self.new("\u{1F1F5 1F1FC}", [:flag_Palau], "FLAG PALAU"),
      self.new("\u{1F1F5 1F1FE}", [:flag_Paraguay], "FLAG PARAGUAY"),
      self.new("\u{1F1F6 1F1E6}", [:flag_Qatar], "FLAG QATAR"),
      self.new("\u{1F1F7 1F1EA}", [:flag_Réunion], "FLAG RÉUNION"),
      self.new("\u{1F1F7 1F1F4}", [:flag_Romania], "FLAG ROMANIA"),
      self.new("\u{1F1F7 1F1F8}", [:flag_Serbia], "FLAG SERBIA"),
      self.new("\u{1F1F7 1F1FA}", [:flag_Russia], "FLAG RUSSIA"),
      self.new("\u{1F1F7 1F1FC}", [:flag_Rwanda], "FLAG RWANDA"),
      self.new("\u{1F1F8 1F1E6}", [:flag_Saudi_Arabia], "FLAG SAUDI ARABIA"),
      self.new("\u{1F1F8 1F1E7}", [:flag_Solomon_Islands], "FLAG SOLOMON ISLANDS"),
      self.new("\u{1F1F8 1F1E8}", [:flag_Seychelles], "FLAG SEYCHELLES"),
      self.new("\u{1F1F8 1F1E9}", [:flag_Sudan], "FLAG SUDAN"),
      self.new("\u{1F1F8 1F1EA}", [:flag_Sweden], "FLAG SWEDEN"),
      self.new("\u{1F1F8 1F1EC}", [:flag_Singapore], "FLAG SINGAPORE"),
      self.new("\u{1F1F8 1F1ED}", [:flag_St_Helena], "FLAG ST HELENA"),
      self.new("\u{1F1F8 1F1EE}", [:flag_Slovenia], "FLAG SLOVENIA"),
      self.new("\u{1F1F8 1F1EF}", [:flag_Svalbard_Jan_Mayen], "FLAG SVALBARD JAN MAYEN"),
      self.new("\u{1F1F8 1F1F0}", [:flag_Slovakia], "FLAG SLOVAKIA"),
      self.new("\u{1F1F8 1F1F1}", [:flag_Sierra_Leone], "FLAG SIERRA LEONE"),
      self.new("\u{1F1F8 1F1F2}", [:flag_San_Marino], "FLAG SAN MARINO"),
      self.new("\u{1F1F8 1F1F4}", [:flag_Somalia], "FLAG SOMALIA"),
      self.new("\u{1F1F8 1F1F7}", [:flag_Suriname], "FLAG SURINAME"),
      self.new("\u{1F1F8 1F1F8}", [:flag_South_Sudan], "FLAG SOUTH SUDAN"),
      self.new("\u{1F1F8 1F1F9}", [:flag_São_Tomé_Príncipe], "FLAG SÃO TOMÉ PRÍNCIPE"),
      self.new("\u{1F1F8 1F1FB}", [:flag_El_Salvador], "FLAG EL SALVADOR"),
      self.new("\u{1F1F8 1F1FD}", [:flag_Sint_Maarten], "FLAG SINT MAARTEN"),
      self.new("\u{1F1F8 1F1FE}", [:flag_Syria], "FLAG SYRIA"),
      self.new("\u{1F1F8 1F1FF}", [:flag_Eswatini], "FLAG ESWATINI"),
      self.new("\u{1F1F9 1F1E6}", [:flag_Tristan_da_Cunha], "FLAG TRISTAN DA CUNHA"),
      self.new("\u{1F1F9 1F1E8}", [:flag_Turks_Caicos_Islands], "FLAG TURKS CAICOS ISLANDS"),
      self.new("\u{1F1F9 1F1E9}", [:flag_Chad], "FLAG CHAD"),
      self.new("\u{1F1F9 1F1EB}", [:flag_French_Southern_Territories], "FLAG FRENCH SOUTHERN TERRITORIES"),
      self.new("\u{1F1F9 1F1EC}", [:flag_Togo], "FLAG TOGO"),
      self.new("\u{1F1F9 1F1ED}", [:flag_Thailand], "FLAG THAILAND"),
      self.new("\u{1F1F9 1F1EF}", [:flag_Tajikistan], "FLAG TAJIKISTAN"),
      self.new("\u{1F1F9 1F1F0}", [:flag_Tokelau], "FLAG TOKELAU"),
      self.new("\u{1F1F9 1F1F1}", [:"flag-Timor-Leste"], "FLAG TIMOR LESTE"),
      self.new("\u{1F1F9 1F1F2}", [:flag_Turkmenistan], "FLAG TURKMENISTAN"),
      self.new("\u{1F1F9 1F1F4}", [:flag_Tonga], "FLAG TONGA"),
      self.new("\u{1F1F9 1F1F7}", [:flag_Turkey], "FLAG TURKEY"),
      self.new("\u{1F1F9 1F1F9}", [:flag_Trinidad_Tobago], "FLAG TRINIDAD TOBAGO"),
      self.new("\u{1F1F9 1F1FB}", [:flag_Tuvalu], "FLAG TUVALU"),
      self.new("\u{1F1F9 1F1FC}", [:flag_Taiwan], "FLAG TAIWAN"),
      self.new("\u{1F1F9 1F1FF}", [:flag_Tanzania], "FLAG TANZANIA"),
      self.new("\u{1F1FA 1F1E6}", [:flag_Ukraine], "FLAG UKRAINE"),
      self.new("\u{1F1FA 1F1EC}", [:flag_Uganda], "FLAG UGANDA"),
      self.new("\u{1F1FA 1F1F2}", [:flag_US_Outlying_Islands], "FLAG US OUTLYING ISLANDS"),
      self.new("\u{1F1FA 1F1F8}", [:flag_United_States], "FLAG UNITED STATES"),
      self.new("\u{1F1FA 1F1FE}", [:flag_Uruguay], "FLAG URUGUAY"),
      self.new("\u{1F1FA 1F1FF}", [:flag_Uzbekistan], "FLAG UZBEKISTAN"),
      self.new("\u{1F1FB 1F1E6}", [:flag_Vatican_City], "FLAG VATICAN CITY"),
      self.new("\u{1F1FB 1F1E8}", [:flag_St_Vincent_Grenadines], "FLAG ST VINCENT GRENADINES"),
      self.new("\u{1F1FB 1F1EA}", [:flag_Venezuela], "FLAG VENEZUELA"),
      self.new("\u{1F1FB 1F1EC}", [:flag_British_Virgin_Islands], "FLAG BRITISH VIRGIN ISLANDS"),
      self.new("\u{1F1FB 1F1EE}", [:flag_US_Virgin_Islands], "FLAG US VIRGIN ISLANDS"),
      self.new("\u{1F1FB 1F1FA}", [:flag_Vanuatu], "FLAG VANUATU"),
      self.new("\u{1F1FC 1F1EB}", [:flag_Wallis_Futuna], "FLAG WALLIS FUTUNA"),
      self.new("\u{1F1FC 1F1F8}", [:flag_Samoa], "FLAG SAMOA"),
      self.new("\u{1F1FD 1F1F0}", [:flag_Kosovo], "FLAG KOSOVO"),
      self.new("\u{1F1FE 1F1EA}", [:flag_Yemen], "FLAG YEMEN"),
      self.new("\u{1F1FE 1F1F9}", [:flag_Mayotte], "FLAG MAYOTTE"),
      self.new("\u{1F1FF 1F1E6}", [:flag_South_Africa], "FLAG SOUTH AFRICA"),
      self.new("\u{1F1FF 1F1F2}", [:flag_Zambia], "FLAG ZAMBIA"),
      self.new("\u{1F1FF 1F1FC}", [:flag_Zimbabwe], "FLAG ZIMBABWE"),
    ]
  end
end